import {VERSION,uid,today,cents,validate,balance,totals,upsert,remove} from './model.mjs';
import {read,mutate} from './storage.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(n/100).toLocaleString('es-AR',{style:'currency',currency:'ARS'});
let data,view='home',month=today().slice(0,7),work='trips',period='month',editing=null,backup=null,ready=false,busy=false;
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('ag-independent'):null;
channel?.addEventListener('message',async()=>{data=await read();render();});
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000);}
async function change(fn){data=await mutate(fn);channel?.postMessage('updated');render();}
const names=(key,id)=>data[key].find(x=>x.id===id)?.name||'—';
function summaryCard(title,value,cls=''){return `<div class="card"><small>${title}</small><strong class="${cls}">${value}</strong></div>`;}
const button=(text,action,extra='')=>`<button data-action="${action}" ${extra}>${text}</button>`;
const monthControl=()=>`<div class="toolbar"><input aria-label="Mes" type="month" id="month" value="${month}">${button('＋ Movimiento','new','class="primary"')}</div>`;
const editButton=(key,id)=>button('Editar','edit',`data-key="${key}" data-id="${esc(id)}"`);
function txList(rows){return rows.length?rows.sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<div class="list-row"><div><strong>${esc(t.description||names('categories',t.category)||(t.kind==='transfer'?'Transferencia':'Movimiento'))}</strong><small>${esc(t.date)} · ${esc(names('accounts',t.account))}</small></div><span class="${t.kind==='expense'?'negative':'positive'}">${t.kind==='expense'?'−':''}${money(t.amount)}</span>${editButton('transactions',t.id)}</div>`).join(''):'<p class="empty">Todavía no hay movimientos en este mes.</p>';}
function home(){const t=totals(data,month),available=data.accounts.reduce((n,a)=>n+balance(data,a.id),0);const grouped=data.categories.filter(c=>c.kind==='expense').map(c=>({...c,total:data.transactions.filter(t=>t.kind==='expense'&&t.category===c.id&&t.date.startsWith(month)).reduce((n,t)=>n+t.amount,0)})).filter(c=>c.total).sort((a,b)=>b.total-a.total);return `${monthControl()}<section class="card hero"><small>Saldo en tus cuentas</small><strong>${money(available)}</strong><span class="muted">Guardado en este teléfono</span></section><div class="metrics">${summaryCard('Ingresos del mes',money(t.income),'positive')}${summaryCard('Gastos del mes',money(t.expense),'negative')}</div><div class="toolbar">${button('Escanear comprobante','scan')}${button('Cuentas','accounts')}</div><section class="card"><h2>En qué gastaste</h2>${grouped.map(c=>`<div class="list-row"><div><div class="row"><span>${esc(c.name)}</span><strong>${money(c.total)}</strong></div><div class="bar"><i style="width:${100*c.total/Math.max(1,t.expense)}%"></i></div></div></div>`).join('')||'<p class="muted">Tus categorías aparecerán al cargar gastos.</p>'}</section><section class="card"><h2>Últimos movimientos</h2>${txList(data.transactions.filter(t=>t.date.startsWith(month)).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</section>`;}
function transactions(){return `${monthControl()}<section class="card">${txList(data.transactions.filter(t=>t.date.startsWith(month)))}</section>`;}
function range(){if(period==='month'){const [y,m]=month.split('-').map(Number);return [month+'-01',month+'-'+new Date(y,m,0).getDate()];}const d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);const start=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);d.setDate(d.getDate()+6);return [start,new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)];}
const inRange=r=>{const [a,b]=range();return r.date>=a&&r.date<=b;};
function workView(){const rows=data[work].filter(inRange),km=data.mileage.filter(inRange),totalKM=km.reduce((n,r)=>n+r.end-r.start,0);let cards='';
 if(work==='trips'||work==='extras'){cards=rows.sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<details class="card" data-open="${r.id}"><summary><strong>${esc(r.client||r.app)}</strong><span>${money(r.amount)}</span>${editButton(work,r.id)}</summary><div class="detail"><small>${r.date}</small>${work==='trips'?`<p>Desde ${esc(r.origin||'Sin origen')}<br>${esc(r.destinations.join(' → '))}<br>${r.stops} paradas</p>${['bulky','rain','flex','own'].map((key,i)=>`<label class="check"><input type="checkbox" data-check="${key}" data-id="${r.id}" ${r[key]?'checked':''}>${['Bulto','Lluvia','Flex','Cliente propio'][i]}</label>`).join('')}`:`<p>${r.minutes/60} h · ${r.orders} pedidos / viajes</p>`}<p>${esc(r.note||'')}</p></div></details>`).join('');}
 if(work==='mileage')cards=rows.map(r=>`<details class="card" data-open="${r.id}"><summary><strong>${r.date}</strong><span>${(r.end-r.start).toFixed(1)} km</span>${editButton(work,r.id)}</summary><p>Inicial: ${r.start} · Final: ${r.end}</p></details>`).join('');
 if(work==='deliveries')cards=data.zones.map(z=>{const deliveries=rows.filter(d=>d.zone===z.id);return `<details class="card" data-open="${z.id}"><summary><strong>${esc(z.name)}</strong><span>${money(deliveries.reduce((n,d)=>n+d.amount,0))}</span></summary><div class="detail"><p>${deliveries.length} envíos · Tarifa: ${money(z.rate)}</p><div class="toolbar">${button('− Último','minus',`data-id="${z.id}"`)}${button('＋ Envío de hoy','delivery',`data-id="${z.id}" class="primary"`)}${editButton('zones',z.id)}</div></div></details>`;}).join('');
 return `<div class="toolbar"><select id="work" aria-label="Herramienta">${[['trips','Viajes'],['extras','Extras'],['mileage','Kilometraje'],['deliveries','Flex por zona']].map(([k,v])=>`<option value="${k}" ${k===work?'selected':''}>${v}</option>`).join('')}</select><select id="period" aria-label="Período"><option value="month" ${period==='month'?'selected':''}>Mes seleccionado</option><option value="week" ${period==='week'?'selected':''}>Esta semana</option></select><input aria-label="Mes" type="month" id="month" value="${month}" ${period==='week'?'disabled':''}></div><div class="metrics">${summaryCard('KM registrados',totalKM.toFixed(1)+' km')}${summaryCard('Promedio por día registrado',km.length?(totalKM/km.length).toFixed(1)+' km':'—')}</div><p class="muted">${range().join(' → ')} · El promedio incluye ${km.length} días con odómetro completo.</p><div class="toolbar">${button(work==='deliveries'?'＋ Zona':'＋ Registro','work-new','class="primary"')}</div><p class="muted">Los importes de Trabajo no se suman automáticamente a tus cuentas. Registralos como ingresos cuando los cobres.</p><div class="grid">${cards||'<p class="empty">No hay registros en este período.</p>'}</div>`;
}
function settings(){return `<section class="card"><h2>Tu información</h2><p>Esta versión funciona en el teléfono. No necesita código de vinculación ni una computadora encendida.</p><div class="toolbar">${button('Cuentas','accounts')}${button('Categorías','categories')}</div></section><section class="card"><h2>Respaldo</h2><p class="muted">Exportá una copia periódicamente. Borrar los datos del sitio o cambiar de navegador puede eliminar la base local. No hay sincronización automática.</p><div class="toolbar">${button('Exportar copia','export')}${button('Importar copia móvil','import')}</div><p class="muted">Este respaldo JSON es propio de Móvil; no reemplaza ni importa la base SQLite de Windows.</p></section><section class="card"><h2>Instalación y uso sin conexión</h2><p id="offline-status">${ready?'Aplicación y OCR disponibles sin conexión.':'Preparando archivos para uso sin conexión…'}</p><p>Android: menú del navegador → Instalar aplicación. iPhone: Safari → Compartir → Agregar a inicio.</p><p class="muted">La primera carga necesita Internet y un enlace HTTPS. Después, los datos y el OCR se procesan en este dispositivo.</p>${button('Solicitar almacenamiento persistente','persist')}</section><section class="card"><h2>Móvil ${VERSION} · Versión inicial</h2><p class="muted">Incluye cuentas, categorías, movimientos, análisis mensual, Viajes, Extras, Flex y kilometraje. Cuotas, recurrentes, importación de Windows y sincronización entre dispositivos todavía no están incorporadas.</p><a href="vendor/versions.json">Bibliotecas incluidas</a></section>`;}
function catalog(key){return `<div class="toolbar">${button('＋ '+(key==='accounts'?'Cuenta':'Categoría'),'catalog-new',`data-key="${key}" class="primary"`)}</div><section class="card">${data[key].map(r=>`<div class="list-row"><div><strong>${esc(r.name)}</strong><small>${key==='accounts'?money(balance(data,r.id)):esc((r.kind==='expense'?'Gasto':'Ingreso')+(r.parent?' · '+names('categories',r.parent):''))}</small></div>${editButton(key,r.id)}</div>`).join('')}</section>`;}
function render(){if(!data)return;const open=[...document.querySelectorAll('details[open]')].map(d=>d.dataset.open);$('#title').textContent=({home:'Tu panorama',transactions:'Movimientos',work:'Tu trabajo',settings:'Tu espacio',accounts:'Cuentas',categories:'Categorías'})[view];$('#content').innerHTML=view==='home'?home():view==='transactions'?transactions():view==='work'?workView():['accounts','categories'].includes(view)?catalog(view):settings();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('details').forEach(d=>d.open=open.includes(d.dataset.open));}
function field(name,label,type='text',value='',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([k,v])=>`<option value="${esc(k)}" ${String(k)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function note(value=''){return `<label>Comentario<textarea name="note">${esc(value)}</textarea></label>`;}
function edit(key,id=null,draft={}){const r=id?data[key].find(x=>x.id===id):draft;editing={key,id};let html='';const amount=(name,label,value=0)=>field(name,label,'number',value/100,'step="0.01"');
 if(key==='transactions'){html=select('kind','Tipo',[['expense','Gasto'],['income','Ingreso'],['transfer','Transferencia']],r.kind||'expense')+field('date','Fecha','date',r.date||today(),'required')+amount('amount','Importe',r.amount||0)+select('account','Cuenta',data.accounts.map(a=>[a.id,a.name]),r.account)+select('category','Categoría',data.categories.filter(c=>c.kind===(r.kind||'expense')).map(c=>[c.id,c.name]),r.category)+select('to','Cuenta de destino (solo transferencias)',data.accounts.map(a=>[a.id,a.name]),r.to)+field('description','Descripción','text',r.description||'')+note(r.note);}
 if(key==='accounts')html=field('name','Nombre','text',r.name||'','required maxlength="200"')+amount('initial','Saldo inicial',r.initial||0);
 if(key==='categories')html=field('name','Nombre','text',r.name||'','required maxlength="200"')+select('kind','Tipo',[['expense','Gasto'],['income','Ingreso']],r.kind||'expense')+select('parent','Dentro de',[['','Principal'],...data.categories.filter(c=>c.id!==id).map(c=>[c.id,c.name])],r.parent);
 if(key==='trips')html=field('client','Cliente','text',r.client||'','required')+field('date','Fecha','date',r.date||today(),'required')+field('origin','Origen','text',r.origin||'')+`<label>Destinos (uno por línea)<textarea name="destinations">${esc((r.destinations||[]).join('\n'))}</textarea></label>`+field('stops','Paradas','number',r.stops||1,'min="1" step="1" required')+amount('amount','Cobrado',r.amount||0)+['bulky','rain','flex','own'].map((key,i)=>`<label class="check"><input name="${key}" type="checkbox" ${r[key]?'checked':''}>${['Bulto','Lluvia','Flex','Cliente propio'][i]}</label>`).join('')+note(r.note);
 if(key==='extras')html=field('app','Aplicación','text',r.app||'','required')+field('date','Fecha','date',r.date||today(),'required')+field('hours','Horas','number',(r.minutes||0)/60,'step="0.01" min="0"')+field('orders','Pedidos / viajes','number',r.orders||0,'min="0" step="1"')+amount('amount','Ganado',r.amount||0)+note(r.note);
 if(key==='mileage')html=field('date','Fecha','date',r.date||today(),'required')+field('start','Odómetro inicial','number',r.start??'','min="0" step="0.1" required')+field('end','Odómetro final','number',r.end??'','min="0" step="0.1" required');
 if(key==='zones')html=field('name','Nombre de zona','text',r.name||'','required')+amount('rate','Tarifa por envío',r.rate||0);
 $('#form-title').textContent=(id?'Editar ':'Nuevo ')+({transactions:'movimiento',accounts:'cuenta',categories:'categoría',trips:'viaje',extras:'extra',mileage:'kilometraje',zones:'zona'})[key];$('#fields').innerHTML=html;$('#form-error').textContent='';$('#delete').hidden=!id;$('#editor').showModal();if(key==='transactions'){const kind=$('[name=kind]');kind.onchange=()=>{const target=$('[name=category]');target.innerHTML=data.categories.filter(c=>c.kind===kind.value).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');target.closest('label').hidden=kind.value==='transfer';$('[name=to]').closest('label').hidden=kind.value!=='transfer';};$('[name=to]').closest('label').hidden=kind.value!=='transfer';$('[name=category]').closest('label').hidden=kind.value==='transfer';}
}
$('#form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),r=Object.fromEntries(f),key=editing.key;r.id=editing.id||uid();try{for(const name of ['amount','initial','rate'])if(name in r)r[name]=cents(r[name]);for(const name of ['orders','start','end','stops'])if(name in r)r[name]=Number(r[name]);if(key==='extras'){r.minutes=Math.round(Number(r.hours)*60);delete r.hours;}if(key==='trips'){r.destinations=r.destinations.split('\n').map(s=>s.trim()).filter(Boolean);for(const k of ['bulky','rain','flex','own'])r[k]=f.has(k);}await change(s=>upsert(s,key,r));$('#editor').close();toast('Guardado en este teléfono.');}catch(e){$('#form-error').textContent=e.message;}};
$('#close').onclick=()=>$('#editor').close();$('#delete').onclick=async()=>{if(!confirm('¿Eliminar este registro?'))return;try{await change(s=>remove(s,editing.key,editing.id));$('#editor').close();}catch(e){$('#form-error').textContent=e.message;}};
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='month'){if(el.value){month=el.value;render();}}if(el.id==='work'){work=el.value;render();}if(el.id==='period'){period=el.value;render();}if(el.dataset.check){try{await change(s=>{const r=s.trips.find(r=>r.id===el.dataset.id);r[el.dataset.check]=el.checked;return s;});}catch(e){toast(e.message);render();}}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();window.scrollTo(0,0);return;}try{const action=b.dataset.action,key=b.dataset.key,id=b.dataset.id;if(action==='new')edit('transactions');if(action==='edit')edit(key,id);if(action==='catalog-new')edit(key);if(action==='work-new')edit(work==='deliveries'?'zones':work);if(action==='accounts'||action==='categories'){view=action;render();}if(action==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`AppGastos-Movil-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(action==='import')$('#backup-file').click();if(action==='persist'){const granted=await navigator.storage?.persist?.();toast(granted?'Almacenamiento persistente habilitado.':'El navegador decide la persistencia. Conservá un respaldo.');}if(action==='scan')$('#scan-file').click();if(action==='delivery')await change(s=>{const z=s.zones.find(z=>z.id===id);s.deliveries.push({id:uid(),zone:id,date:today(),amount:z.rate});return s;});if(action==='minus'){await change(s=>{const matches=s.deliveries.filter(d=>d.zone===id&&inRange(d));const last=matches.at(-1);if(last)s.deliveries=s.deliveries.filter(d=>d.id!==last.id);return s;});}}catch(e){toast(e.message);}});
$('#backup-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20e6)throw Error('La copia supera 20 MB.');backup=validate(JSON.parse(await file.text()));if(confirm(`Esta copia contiene ${backup.transactions.length} movimientos y ${backup.accounts.length} cuentas. Reemplazará TODOS los datos móviles actuales. Exportá tu copia antes de continuar. ¿Importar?`)){await change(()=>backup);toast('Copia importada.');}}catch(e){toast(e.message);}finally{e.target.value='';backup=null;}};
$('#scan-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy)return;busy=true;toast('Leyendo comprobante en este teléfono…');try{const {scan}=await import('./ocr.mjs');const text=await scan(file,message=>{ $('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);});const lines=text.split('\n').filter(x=>/total/i.test(x)&&!/sub.?total/i.test(x));const match=lines.at(-1)?.match(/(\d[\d.,]*[.,]\d{2})(?!\d)/g)?.at(-1);let value=0;if(match){const decimal=match.lastIndexOf(',')>match.lastIndexOf('.')?',':'.';value=cents(match.replace(decimal===','?/\./g:/,/g,'').replace(',','.'));}edit('transactions',null,{description:'Comprobante escaneado',amount:value,note:text});toast('Revisá importe, fecha y categoría antes de guardar.');}catch(e){toast('No se pudo leer: '+(e.message||String(e)));}finally{busy=false;}};
async function start(){try{data=await read();await mutate(s=>s);render();if('serviceWorker'in navigator){await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;ready=true;if(view==='settings')render();}else toast('Este navegador no permite preparar el modo sin conexión.');}catch(e){$('#content').textContent='No se pudo preparar el almacenamiento local: '+e.message;}}
start();
