import {workScreen,workConfiguration} from './work-ui.mjs';
import * as desktop from './desktop-ui.mjs';
import {registerDue,categoryPath,advance} from './planning.mjs';
import {VERSION,uid,today,cents,validate,historyRows,balance,totals,upsert,remove} from './model.mjs';
import {read,mutate} from './storage.mjs';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>(n/100).toLocaleString('es-AR',{style:'currency',currency:'ARS'});
let workQuery='',txQuery='',txKind='all',txAccount='';
let categoryKind='expense',categorySearch='',analysisKind='expense',calendarDay='',reviewing=null;
let data,view='home',month=today().slice(0,7),work='trips',period='month',editing=null,backup=null,ready=false,busy=false;
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('ag-independent'):null;
channel?.addEventListener('message',async()=>{data=await read();render();});
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000);}
async function change(fn){data=await mutate(fn);channel?.postMessage('updated');render();}
const names=(key,id)=>data[key].find(x=>x.id===id)?.name||'—';
function summaryCard(title,value,cls=''){return `<div class="card"><small>${title}</small><strong class="${cls}">${value}</strong></div>`;}
const button=(text,action,extra='')=>`<button data-action="${action}" ${extra}>${text}</button>`;
const monthControl=()=>`<div class="toolbar"><input aria-label="Mes" type="month" id="month" value="${month}">${button('＋ Movimiento','new','class="primary"')}</div>`;
const editButton=(key,id)=>button('Editar','edit',`data-key="${key}" data-id="${esc(id)}"`);
function txList(rows){return rows.length?rows.sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<div class="list-row">${desktop.icon(data.categories.find(c=>c.id===t.category)?.icon||'transfer',data.categories.find(c=>c.id===t.category)?.color)}<div><strong>${esc(t.description||names('categories',t.category)||(t.kind==='transfer'?'Transferencia':'Movimiento'))}</strong><small>${esc(t.date)} · ${esc(names('accounts',t.account))}</small></div><span class="${t.kind==='expense'?'negative':'positive'}">${t.kind==='expense'?'−':''}${money(t.amount)}</span>${editButton('transactions',t.id)}</div>`).join(''):'<p class="empty">Todavía no hay movimientos en este mes.</p>';}
function home(){const t=totals(data,month),available=data.accounts.filter(a=>a.include!==false&&!a.archived).reduce((n,a)=>n+balance(data,a.id),0);const grouped=data.categories.filter(c=>c.kind==='expense').map(c=>({...c,total:[...data.transactions,...historyRows(data)].filter(t=>t.kind==='expense'&&t.category===c.id&&t.date.startsWith(month)).reduce((n,t)=>n+t.amount,0)})).filter(c=>c.total).sort((a,b)=>b.total-a.total);return `${monthControl()}<section class="card hero"><small>SALDO DISPONIBLE</small><strong>${money(available)}</strong><span class="muted">Guardado en este teléfono</span></section><div class="metrics">${summaryCard('Ingresos del mes',money(t.income),'positive')}${summaryCard('Gastos del mes',money(t.expense),'negative')}</div><div class="toolbar">${button('Escanear comprobante','scan')}${button('Cuentas','accounts')}<button data-view="stats">Ver análisis</button></div><section class="card"><h2>En qué gastaste</h2>${grouped.map(c=>`<div class="list-row">${desktop.icon(c.icon,c.color)}<div><div class="row"><span>${esc(c.name)}</span><strong>${money(c.total)}</strong></div><div class="bar"><i style="width:${100*c.total/Math.max(1,t.expense)}%"></i></div></div></div>`).join('')||'<p class="muted">Tus categorías aparecerán al cargar gastos.</p>'}</section><section class="card"><h2>Últimos movimientos</h2>${txList(data.transactions.filter(t=>t.date.startsWith(month)).slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</section>`;}
function transactions(){return `${monthControl()}<div class="filter-strip"><input id="tx-search" type="search" aria-label="Buscar movimientos" value="${esc(txQuery)}" placeholder="Buscar descripción, categoría o nota…"><select id="tx-kind" aria-label="Tipo de movimientos">${[['all','Todos'],['expense','Gastos'],['income','Ingresos'],['transfer','Transferencias']].map(([k,t])=>`<option value="${k}" ${txKind===k?'selected':''}>${t}</option>`).join('')}</select><select id="tx-account" aria-label="Filtrar por cuenta"><option value="">Todas las cuentas</option>${data.accounts.map(a=>`<option value="${a.id}" ${a.id===txAccount?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><section class="card">${txList(data.transactions.filter(t=>t.date.startsWith(month)&&(txKind==='all'||t.kind===txKind)&&(!txAccount||t.account===txAccount||t.to===txAccount)&&`${t.description} ${t.note} ${categoryPath(data,t.category)}`.toLocaleLowerCase().includes(txQuery.toLocaleLowerCase())))}</section>`;}
function range(){if(period==='month'){const [y,m]=month.split('-').map(Number);return [month+'-01',month+'-'+new Date(y,m,0).getDate()];}const d=new Date();d.setDate(d.getDate()-(d.getDay()+6)%7);const start=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);d.setDate(d.getDate()+6);return [start,new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)];}
const inRange=r=>{const [a,b]=range();return r.date>=a&&r.date<=b;};
function workView(){return workScreen(data,work,period,month,range(),workQuery);}
function settings(){return `<section class="card"><h2>Apariencia</h2><div class="toolbar"><button data-action="theme" data-theme="dark">Oscuro</button><button data-action="theme" data-theme="light">Claro</button></div></section><section class="card"><h2>Tu información</h2><p>Esta versión funciona en el teléfono. No necesita código de vinculación ni una computadora encendida.</p><div class="toolbar">${button('Cuentas','accounts')}${button('Categorías','categories')}</div></section><section class="card"><h2>Respaldo</h2><p class="muted">Exportá una copia periódicamente. Borrar los datos del sitio o cambiar de navegador puede eliminar la base local. No hay sincronización automática.</p><div class="toolbar">${button('Exportar copia','export')}${button('Importar copia','import')}</div><p class="muted">Para traer tus datos: en Desktop → Móvil → Exportar datos para el teléfono. Importá aquí el JSON. No se modifica la base original de Windows.</p></section><section class="card"><h2>Instalación y uso sin conexión</h2><p id="offline-status">${ready?'Aplicación y OCR disponibles sin conexión.':'Preparando archivos para uso sin conexión…'}</p><p>Android: menú del navegador → Instalar aplicación. iPhone: Safari → Compartir → Agregar a inicio.</p><p class="muted">La primera carga necesita Internet y un enlace HTTPS. Después, los datos y el OCR se procesan en este dispositivo.</p>${button('Solicitar almacenamiento persistente','persist')}</section><section class="card"><h2>App Gastos ${VERSION} · Móvil</h2><p class="muted">Incluye cuentas, categorías, movimientos, análisis mensual, Viajes, Extras, Flex y kilometraje. Incluye cuotas, recurrentes, calendario y presupuestos. La sincronización automática entre dispositivos todavía no está activada.</p><a href="vendor/versions.json">Bibliotecas incluidas</a></section>`;}
function catalog(key){return key==='accounts'?desktop.accountCards(data):desktop.categoryCards(data,categoryKind,categorySearch);}
function render(){if(!data)return;const open=[...document.querySelectorAll('details[open]')].map(d=>d.dataset.open);const page=desktop.pages.find(p=>p[0]===view);$('#title').textContent=page?.[1]||({work:'Viajes',flex:'Flex',more:'Todas las secciones',budgets:'Presupuestos'})[view]||'App Gastos';$('#subtitle').textContent=page?.[3]||'Tu trabajo y tus finanzas, organizados';$('#content').innerHTML=view==='home'?home():view==='transactions'?transactions():['work','flex'].includes(view)?workView():['accounts','categories'].includes(view)?catalog(view):view==='stats'?desktop.analysis(data,month,analysisKind):view==='calendar'?desktop.calendar(data,month,calendarDay):['installments','recurring'].includes(view)?desktop.planningCards(data,view):view==='budgets'?desktop.budgetCards(data,month):view==='work-config'?workConfiguration(data):view==='tools'?desktop.tools():view==='more'?desktop.more():view==='review'?desktop.review(data):settings();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('details').forEach(d=>{if(open.includes(d.dataset.open))d.open=true;});}
function field(name,label,type='text',value='',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(name,label,options,value){return `<label>${esc(label)}<select name="${name}">${options.map(([k,v])=>`<option value="${esc(k)}" ${String(k)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function note(value=''){return `<label>Comentario<textarea name="note">${esc(value)}</textarea></label>`;}
function edit(key,id=null,draft={}){const r=id?data[key].find(x=>x.id===id):draft;editing={key,id};let html='';const amount=(name,label,value=0)=>field(name,label,'number',value/100,'step="0.01"');
 if(key==='transactions'||key==='recurring'){html=select('kind','Tipo',[['expense','Gasto'],['income','Ingreso'],['transfer','Transferencia']],r.kind||'expense')+field('date','Fecha','date',r.date||today(),'required')+amount('amount','Importe',r.amount||0)+select('account','Cuenta',data.accounts.map(a=>[a.id,a.name]),r.account)+select('category','Categoría',data.categories.filter(c=>c.kind===(r.kind||'expense')).map(c=>[c.id,categoryPath(data,c.id)]),r.category)+select('to','Cuenta de destino (solo transferencias)',data.accounts.map(a=>[a.id,a.name]),r.to)+field('description','Descripción','text',r.description||'')+note(r.note);if(key==='recurring')html+=field('next_date','Próximo vencimiento','date',r.next_date||today(),'required')+select('frequency','Frecuencia',[['daily','Diaria'],['weekly','Semanal'],['monthly','Mensual'],['yearly','Anual']],r.frequency||'monthly')+field('interval','Cada cuántos períodos','number',r.interval||1,'min="1" max="365"')+`<label class="check"><input type="checkbox" name="active" ${r.active!==false?'checked':''}>Activo</label>`;}
 if(key==='accounts')html=field('name','Nombre','text',r.name||'','required maxlength="200"')+select('type','Tipo',[['Cuenta','Cuenta'],['Efectivo','Efectivo'],['Banco','Banco'],['Billetera','Billetera'],['Ahorro','Ahorro'],['Tarjeta','Tarjeta']],r.type||'Cuenta')+amount('initial','Saldo inicial',r.initial||0)+desktop.visualFields(r)+`<label class="check"><input name="include" type="checkbox" ${r.include!==false?'checked':''}>Incluir en saldo disponible</label><label class="check"><input name="archived" type="checkbox" ${r.archived?'checked':''}>Archivada</label>`+amount('credit_limit','Límite de tarjeta',r.credit_limit||0)+field('closing_day','Día de cierre','number',r.closing_day||'','min="1" max="31"')+field('due_day','Día de vencimiento','number',r.due_day||'','min="1" max="31"');
 if(key==='categories')html=field('name','Nombre','text',r.name||'','required maxlength="200"')+select('kind','Tipo',[['expense','Gasto'],['income','Ingreso']],r.kind||'expense')+select('parent','Dentro de',[['','Principal'],...data.categories.filter(c=>c.id!==id).map(c=>[c.id,categoryPath(data,c.id)])],r.parent)+desktop.visualFields(r);
 if(key==='trips')html=field('client','Cliente','text',r.client||'','required')+field('date','Fecha','date',r.date||today(),'required')+field('origin','Origen','text',r.origin||'')+`<label>Destinos (uno por línea)<textarea name="destinations">${esc((r.destinations||[]).join('\n'))}</textarea></label>`+field('stops','Paradas','number',r.stops||1,'min="1" step="1" required')+amount('amount','Cobrado',r.amount||0)+['bulky','rain','flex','own'].map((key,i)=>`<label class="check"><input name="${key}" type="checkbox" ${r[key]?'checked':''}>${['Bulto','Lluvia','Flex','Cliente propio'][i]}</label>`).join('')+note(r.note);
 if(key==='trips')html+=data.workFields.filter(f=>f.active).map(f=>f.type==='check'?`<label class="check"><input type="checkbox" name="custom:${f.id}" ${r.custom?.[f.id]?'checked':''}>${esc(f.name)}</label>`:f.type==='options'?select('custom:'+f.id,f.name,(f.options||'').split(',').map(v=>[v.trim(),v.trim()]),r.custom?.[f.id]):field('custom:'+f.id,esc(f.name),f.type==='money'?'number':f.type,r.custom?.[f.id]||'',f.type==='money'?'step="0.01"':'' )).join('');
 if(key==='extras')html=field('app','Aplicación','text',r.app||'','required')+field('date','Fecha','date',r.date||today(),'required')+field('hours','Horas','number',(r.minutes||0)/60,'step="0.01" min="0"')+field('orders','Pedidos / viajes','number',r.orders||0,'min="0" step="1"')+amount('amount','Ganado',r.amount||0)+note(r.note);
 if(key==='mileage')html=field('date','Fecha','date',r.date||today(),'required')+field('start','Odómetro inicial','number',r.start??'','min="0" step="0.1" required')+field('end','Odómetro final','number',r.end??'','min="0" step="0.1" required');
 if(key==='zones')html=field('name','Nombre de zona','text',r.name||'','required')+amount('rate','Tarifa por envío',r.rate||0);
 if(key==='installments')html=field('description','Descripción','text',r.description||'','required')+select('account','Cuenta',data.accounts.map(a=>[a.id,a.name]),r.account)+select('category','Categoría',data.categories.filter(c=>c.kind==='expense').map(c=>[c.id,categoryPath(data,c.id)]),r.category)+amount('total','Importe total',r.total||0)+field('count','Cantidad de cuotas','number',r.count||3,'min="2" max="360" required')+field('first_date','Primera cuota','date',r.first_date||today(),'required')+field('next_number','Próxima cuota a registrar','number',r.next_number||1,'min="1" required')+`<label class="check"><input name="active" type="checkbox" ${r.active!==false?'checked':''}>Activo</label>`+note(r.note);
 if(key==='budgets')html=field('name','Nombre','text',r.name||'','required')+amount('amount','Límite mensual',r.amount||0)+field('date','Fecha de inicio','date',r.date||today(),'required')+select('account','Cuenta',[['','Todas'],...data.accounts.map(a=>[a.id,a.name])],r.account)+select('category','Categoría',[['','Todas'],...data.categories.filter(c=>c.kind==='expense').map(c=>[c.id,categoryPath(data,c.id)])],r.category);
 if(key==='workFields')html=field('name','Nombre del campo','text',r.name||'','required')+select('type','Tipo',[['check','Casilla Sí / No'],['text','Texto'],['number','Número'],['money','Importe'],['email','Email'],['tel','Teléfono'],['options','Lista de opciones']],r.type||'check')+field('options','Opciones separadas por coma','text',r.options||'')+`<label class="check"><input name="active" type="checkbox" ${r.active!==false?'checked':''}>Activo</label><label class="check"><input name="summary" type="checkbox" ${r.summary!==false?'checked':''}>Mostrar en resumen</label>`;
 $('#form-title').textContent=(id?'Editar ':'Nuevo ')+({transactions:'movimiento',accounts:'cuenta',categories:'categoría',trips:'viaje',extras:'extra',mileage:'kilometraje',zones:'zona',recurring:'recurrente',installments:'compra en cuotas',budgets:'presupuesto',workFields:'campo personalizado'})[key];$('#fields').innerHTML=html;$('#form-error').textContent='';$('#delete').hidden=!id;$('#editor').showModal();if(key==='transactions'||key==='recurring'){const kind=$('[name=kind]');kind.onchange=()=>{const target=$('[name=category]');target.innerHTML=data.categories.filter(c=>c.kind===kind.value).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');target.closest('label').hidden=kind.value==='transfer';$('[name=to]').closest('label').hidden=kind.value!=='transfer';};$('[name=to]').closest('label').hidden=kind.value!=='transfer';$('[name=category]').closest('label').hidden=kind.value==='transfer';}
}
$('#form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),r=Object.fromEntries(f),key=editing.key;r.id=editing.id||uid();try{for(const name of ['amount','initial','rate','total','credit_limit'])if(name in r)r[name]=cents(r[name]);for(const name of ['orders','start','end','stops','count','next_number','interval','closing_day','due_day'])if(name in r)r[name]=Number(r[name]);if(key==='extras'){r.minutes=Math.round(Number(r.hours)*60);delete r.hours;}if(key==='trips'){r.custom={...(data.trips.find(t=>t.id===editing.id)?.custom||{})};for(const def of data.workFields.filter(f=>f.active)){r.custom[def.id]=def.type==='check'?f.has('custom:'+def.id):f.get('custom:'+def.id);delete r['custom:'+def.id];}r.destinations=r.destinations.split('\n').map(s=>s.trim()).filter(Boolean);for(const k of ['bulky','rain','flex','own'])r[k]=f.has(k);}if(key==='accounts'){r.include=f.has('include');r.archived=f.has('archived');}if(['recurring','installments','workFields'].includes(key))r.active=f.has('active');if(key==='workFields')r.summary=f.has('summary');if(key==='recurring')r.anchor=Number(r.next_date.slice(8));await change(s=>{upsert(s,key,{...(s[key].find(x=>x.id===r.id)||{}),...r});if(reviewing&&key==='transactions')s.review=s.review.filter(x=>x.id!==reviewing);return s;});reviewing=null;$('#editor').close();toast('Guardado en este teléfono.');}catch(e){$('#form-error').textContent=e.message;}};
$('#close').onclick=()=>{$('#editor').close();reviewing=null;};$('#delete').onclick=async()=>{if(!confirm('¿Eliminar este registro?'))return;try{await change(s=>remove(s,editing.key,editing.id));$('#editor').close();}catch(e){$('#form-error').textContent=e.message;}};
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='tx-search'){txQuery=el.value;render();}if(el.id==='tx-kind'){txKind=el.value;render();}if(el.id==='tx-account'){txAccount=el.value;render();}if(el.id==='work-search'){workQuery=el.value;render();}if(el.id==='category-kind'){categoryKind=el.value;render();}if(el.id==='category-search'){categorySearch=el.value;render();}if(el.id==='analysis-kind'){analysisKind=el.value;render();}if(el.id==='month'){if(el.value){month=el.value;render();}}if(el.id==='work'){work=el.value;render();}if(el.id==='period'){period=el.value;render();}if(el.dataset.check){try{await change(s=>{const r=s.trips.find(r=>r.id===el.dataset.id);r[el.dataset.check]=el.checked;return s;});}catch(e){toast(e.message);render();}}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;if(view==='flex')work='deliveries';if(view==='work')work='trips';render();window.scrollTo(0,0);return;}try{const action=b.dataset.action,key=b.dataset.key,id=b.dataset.id;if(action==='theme'){document.body.classList.toggle('light',b.dataset.theme==='light');localStorage.setItem('ag-mobile-theme',b.dataset.theme);}if(action==='work-mode'){work=b.dataset.mode;render();}if(action==='work-config'){view='work-config';render();}if(action==='calendar-day'){calendarDay=b.dataset.date;render();}if(action==='category-up')await change(s=>{const c=s.categories.find(c=>c.id===id);const parent=s.categories.find(p=>p.id===c.parent);c.parent=parent?.parent||'';return s;});if(action==='subcategory')edit('categories',null,{parent:id,kind:data.categories.find(c=>c.id===id).kind,color:data.categories.find(c=>c.id===id).color});if(action==='register-due'){await change(s=>registerDue(s,today()));toast('Vencimientos registrados sin duplicados.');}if(action==='review-edit'){reviewing=id;edit('transactions',null,data.review.find(r=>r.id===id));}if(action==='review-remove')await change(s=>{s.review=s.review.filter(r=>r.id!==id);return s;});if(action==='new')edit('transactions');if(action==='edit')edit(key,id);if(action==='catalog-new')edit(key);if(action==='work-new')edit(work==='deliveries'?'zones':work);if(action==='accounts'||action==='categories'){view=action;render();}if(action==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`AppGastos-Movil-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(action==='import')$('#backup-file').click();if(action==='persist'){const granted=await navigator.storage?.persist?.();toast(granted?'Almacenamiento persistente habilitado.':'El navegador decide la persistencia. Conservá un respaldo.');}if(action==='scan')$('#scan-file').click();if(action==='delivery')await change(s=>{const z=s.zones.find(z=>z.id===id);s.deliveries.push({id:uid(),zone:id,date:today(),amount:z.rate});return s;});if(action==='minus'){await change(s=>{const matches=s.deliveries.filter(d=>d.zone===id&&inRange(d));const last=matches.at(-1);if(last)s.deliveries=s.deliveries.filter(d=>d.id!==last.id);return s;});}}catch(e){toast(e.message);}});
$('#backup-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20e6)throw Error('La copia supera 20 MB.');backup=validate(JSON.parse(await file.text()));if(confirm(`Esta copia contiene ${backup.transactions.length} movimientos y ${backup.accounts.length} cuentas. Reemplazará TODOS los datos móviles actuales. Exportá tu copia antes de continuar. ¿Importar?`)){await change(()=>backup);toast('Copia importada.');}}catch(e){toast(e.message);}finally{e.target.value='';backup=null;}};
$('#scan-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy)return;busy=true;toast('Leyendo comprobante en este teléfono…');try{const {scan}=await import('./ocr.mjs');const text=await scan(file,message=>{ $('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);});const lines=text.split('\n').filter(x=>/total/i.test(x)&&!/sub.?total/i.test(x));const match=lines.at(-1)?.match(/(\d[\d.,]*[.,]\d{2})(?!\d)/g)?.at(-1);let value=0;if(match){const decimal=match.lastIndexOf(',')>match.lastIndexOf('.')?',':'.';value=cents(match.replace(decimal===','?/\./g:/,/g,'').replace(',','.'));}const draft={id:uid(),kind:'expense',date:today(),account:data.accounts[0]?.id||'',category:data.categories.find(c=>c.kind==='expense')?.id||'',description:'Comprobante escaneado',amount:value,note:text};await change(s=>{s.review.push(draft);return s;});reviewing=draft.id;edit('transactions',null,draft);toast('Revisá importe, fecha y categoría antes de guardar.');}catch(e){toast('No se pudo leer: '+(e.message||String(e)));}finally{busy=false;}};
async function start(){try{document.body.classList.toggle('light',localStorage.getItem('ag-mobile-theme')==='light');data=await read();await mutate(s=>s);$('#sidebar').innerHTML=desktop.navigation();$('#bottom-nav').innerHTML=desktop.bottomNav();render();if('serviceWorker'in navigator){await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;ready=true;if(view==='settings')render();}else toast('Este navegador no permite preparar el modo sin conexión.');}catch(e){$('#content').textContent='No se pudo preparar el almacenamiento local: '+e.message;}}
start();
