import {balance,totals,historyRows} from './model.mjs';
import {descendants} from './planning.mjs';
import {shiftPeriod,periodLabel} from './periods.mjs';
import {icon,esc,money,color} from './desktop-ui.mjs';

export function dashboardData(s,month){
 const rows=[...s.transactions,...historyRows(s)].filter(t=>t.kind==='expense'&&t.date.startsWith(month));
 const groups=s.categories.filter(c=>c.kind==='expense'&&!c.parent).map(c=>{const ids=descendants(s,c.id);return {...c,total:rows.filter(t=>ids.has(t.category)).reduce((n,t)=>n+t.amount,0)};}).filter(c=>c.total).sort((a,b)=>b.total-a.total);
 const assigned=groups.reduce((n,c)=>n+c.total,0),total=rows.reduce((n,t)=>n+t.amount,0);
 if(total>assigned)groups.push({id:'uncategorized',name:'Sin categoría',color:'#8498af',icon:'other',total:total-assigned});
 return {groups,trend:Array.from({length:6},(_,i)=>{const date=shiftPeriod('month',month+'-01',i-5),key=date.slice(0,7);return {month:key,label:periodLabel('month',date),...totals(s,key)};})};
}
const changeHint=(n,p)=>p?`${Math.abs((n-p)/p*100).toFixed(0)}% ${n>=p?'más':'menos'} vs. mes anterior`:n?'Sin comparación anterior':'Sin movimientos';
export function dashboard(s,month,recent){
 const total=totals(s,month),previous=totals(s,shiftPeriod('month',month+'-01',-1).slice(0,7)),{groups,trend}=dashboardData(s,month),accounts=s.accounts.filter(a=>!a.archived),available=accounts.filter(a=>a.include!==false);
 const scale=Math.max(1,...trend.flatMap(t=>[t.income,t.expense]));let offset=0;
 const segments=groups.map(c=>{const start=offset;offset+=c.total/Math.max(1,total.expense)*100;return `${color(c.color)} ${start}% ${offset}%`;});
 const stat=(label,value,hint,tone)=>`<div class="overview-stat"><small>${label}</small><strong class="${tone}">${money(value)}</strong><small>${hint}</small></div>`;
 return `<div class="dashboard-overview"><section class="card hero"><small>SALDO DISPONIBLE</small><strong>${money(available.reduce((n,a)=>n+balance(s,a.id),0))}</strong><p>${available.length} cuentas disponibles · ${accounts.length-available.length} separadas</p><small>Cuentas separadas no alteran este saldo</small></section><section class="card month-overview"><h2>Este mes</h2><div class="overview-stats">${stat('Ingresos',total.income,changeHint(total.income,previous.income),'positive')}${stat('Gastos',total.expense,changeHint(total.expense,previous.expense),'negative')}${stat('Resultado',total.net,'Ingresos − gastos',total.net>=0?'positive':'negative')}</div></section></div>
 <div class="section-heading"><div><h2>Cuentas</h2><small>Disponible y separado, a simple vista</small></div><button class="quiet" data-view="accounts">Ver todas →</button></div><div class="wallet-grid">${accounts.slice(0,5).map(a=>`<button class="card wallet-mini" data-action="edit" data-key="accounts" data-id="${esc(a.id)}"><span class="wallet-title">${icon(a.icon||'wallet',a.color)}<strong>${esc(a.name)}</strong></span><b>${money(balance(s,a.id))}</b><small>${a.include===false?'Separada':'Disponible'}</small></button>`).join('')}</div>
 <div class="dashboard-charts"><section class="card"><div class="section-heading"><div><h2>Gastos por categoría</h2><small>Qué se llevó la mayor parte del mes</small></div></div>${groups.length?`<div class="category-chart"><div class="donut" role="img" aria-label="Gastos del mes: ${money(total.expense)}" style="background:conic-gradient(${segments.join(',')})"><div><small>Gastos</small><strong>${money(total.expense)}</strong></div></div><div class="chart-legend">${groups.slice(0,7).map(c=>`<div><i style="background:${color(c.color)}"></i><span>${esc(c.name)}</span><b>${Math.round(c.total/total.expense*100)}%</b></div>`).join('')}${groups.length>7?`<small>Y ${groups.length-7} categorías más</small>`:''}</div></div><button class="quiet" data-view="stats">Ver análisis completo →</button>`:'<p class="empty">Tus categorías aparecerán al cargar gastos.</p>'}</section>
 <section class="card"><h2>Flujo de los últimos 6 meses</h2><small>Ingresos y gastos para ver la tendencia</small><div class="cashflow-legend"><span>● Ingresos</span><span>● Gastos</span></div><div class="cashflow-chart">${trend.map(t=>`<div class="cashflow-month"><div class="cashflow-bars" role="img" aria-label="${t.label}: ingresos ${money(t.income)}, gastos ${money(t.expense)}"><i class="income-bar" style="height:${t.income/scale*100}%"></i><i class="expense-bar" style="height:${t.expense/scale*100}%"></i></div><small>${new Date(t.month+'-01T12:00:00').toLocaleDateString('es-AR',{month:'short'})}</small></div>`).join('')}</div><details class="chart-values"><summary>Ver importes por mes</summary>${trend.map(t=>`<div><span>${esc(t.label)}</span><b class="positive">${money(t.income)}</b><b class="negative">${money(t.expense)}</b></div>`).join('')}</details></section></div>
 <div class="dashboard-bottom"><section class="card"><div class="section-heading"><h2>Actividad reciente</h2><button class="quiet" data-view="transactions">Ver todos →</button></div>${recent}</section><section class="card"><h2>Cuotas activas</h2><small>Compromisos que siguen corriendo</small>${s.installments.filter(p=>p.active).slice(0,4).map(p=>`<div class="list-row"><div><strong>${esc(p.description)}</strong><small>${p.next_number-1} de ${p.count} registradas</small></div><b>${money(p.total)}</b></div>`).join('')||'<p class="empty">No hay cuotas activas.</p>'}<button class="quiet" data-view="installments">Ver cuotas →</button></section></div>`;
}
