import {palette,iconCatalog} from './design.mjs';
import {balance,totals,today,historyRows} from './model.mjs';
import {categoryPath,descendants,dueItems} from './planning.mjs';
export const pages=[['home','Dashboard','chart','Tu dinero, de un vistazo'],['transactions','Movimientos','transfer','Todos tus gastos, ingresos y transferencias'],['calendar','Calendario','receipt','Movimientos y próximos vencimientos'],['review','Por revisar','receipt','Comprobantes pendientes de confirmar'],['accounts','Cuentas','wallet','Separá el dinero disponible de tus ahorros'],['installments','Cuotas','card','Compras y compromisos de los próximos meses'],['stats','Análisis','chart','Tus gastos e ingresos, ordenados para entenderlos'],['categories','Categorías','home','Organizá categorías y subcategorías'],['recurring','Recurrentes','transfer','Gastos e ingresos que se repiten'],['tools','Herramientas','tools','Tu trabajo, organizado'],['settings','Ajustes','tools','Apariencia, respaldos y dispositivos']];
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>(n/100).toLocaleString('es-AR',{style:'currency',currency:'ARS'});
export const color=c=>/^#[0-9a-f]{6}$/i.test(c||'')?c:'#7A78E8';
function nearest(c){const n=parseInt(color(c).slice(1),16),rgb=[n>>16,(n>>8)&255,n&255];return palette.map((p,i)=>{const v=parseInt(p.slice(1),16);return [i,[v>>16,(v>>8)&255,v&255].reduce((s,v,k)=>s+(v-rgb[k])**2,0)];}).sort((a,b)=>a[1]-b[1])[0][0];}
export function icon(key='wallet',accent='#7A78E8'){let index=iconCatalog.findIndex(([k])=>k===key);if(index<0)index=iconCatalog.findIndex(([k])=>k==='other');return `<span class="illustrated" aria-hidden="true" style="background-image:url('icons/catalog-${nearest(accent)}.png');background-size:1000% 900%;background-position:${index%10/9*100}% ${Math.floor(index/10)/8*100}%"></span>`;}

const nav=(view,label,ico)=>`<button data-view="${view}">${icon(ico)}<span>${label}</span></button>`;
export function navigation(){return `<div class="brand">${icon('wallet')}<b>App Gastos</b></div>${pages.map(([k,t,i])=>nav(k,t,i)).join('')}`;}
export function bottomNav(){return [['home','Inicio','chart'],['transactions','Movimientos','transfer'],['tools','Trabajo','tools'],['more','Más','other']].map(([v,t,i])=>nav(v,t,i)).join('');}
const edit=(key,id)=>`<button class="quiet" data-action="edit" data-key="${key}" data-id="${esc(id)}">Editar</button>`;
const add=(key,label)=>`<button class="primary" data-action="catalog-new" data-key="${key}">＋ ${label}</button>`;
const metric=(label,value)=>`<div class="card metric"><small>${label}</small><strong>${value}</strong></div>`;
const empty=text=>`<p class="empty">${text}</p>`;
export function accountCards(s){return `<div class="toolbar">${add('accounts','Nueva cuenta')}</div><div class="metrics">${metric('Saldo disponible',money(s.accounts.filter(a=>a.include!==false&&!a.archived).reduce((n,a)=>n+balance(s,a.id),0)))}${metric('Cuentas separadas',money(s.accounts.filter(a=>a.include===false&&!a.archived).reduce((n,a)=>n+balance(s,a.id),0)))}</div><div class="grid account-grid">${s.accounts.map(a=>`<article class="card account-card" style="--account-color:${color(a.color)}"><div class="account-top">${icon(a.icon||({Ahorro:'piggy-bank',Efectivo:'coins',Tarjeta:'card',Banco:'bank',Billetera:'wallet'})[a.type]||'wallet',a.color)}<div><h3>${esc(a.name)}</h3><small>${esc(a.type||'Cuenta')}</small></div>${edit('accounts',a.id)}</div><strong class="account-balance">${money(balance(s,a.id))}</strong><small>Saldo inicial · ${money(a.initial)}</small><div class="row"><span class="badge">${a.archived?'Archivada':a.include===false?'Separada':'Disponible'}</span>${a.type==='Tarjeta'?`<small>Cierra ${a.closing_day||'—'} · Vence ${a.due_day||'—'}</small>`:''}</div></article>`).join('')}</div>`;}
export function categoryCards(s,kind='expense',query=''){
 const q=query.toLocaleLowerCase();const included=c=>!q||categoryPath(s,c.id).toLocaleLowerCase().includes(q)||[...descendants(s,c.id)].some(id=>categoryPath(s,id).toLocaleLowerCase().includes(q));
 function branch(c,depth=0){const children=s.categories.filter(x=>x.parent===c.id&&included(x));return `<details class="category-node ${depth?'':'card'}" data-open="category:${esc(c.id)}" ${q?'open':''}><summary>${icon(c.icon||'star',c.color)}<span class="node-title"><strong>${esc(c.name)}</strong>${children.length?`<small>${children.length} subcategorías</small>`:''}</span>${c.parent?`<button class="quiet" data-action="category-up" data-id="${esc(c.id)}" aria-label="Subir ${esc(c.name)} un nivel">↑</button>`:''}<button class="quiet" data-action="category-move" data-id="${esc(c.id)}" aria-label="Mover ${esc(c.name)}">↗</button>${edit('categories',c.id)}</summary><div class="category-children">${children.map(x=>branch(x,depth+1)).join('')}<button class="quiet" data-action="subcategory" data-id="${esc(c.id)}">＋ Subcategoría</button></div></details>`;}
 return `<div class="toolbar">${add('categories','Nueva categoría')}<select id="category-kind" aria-label="Tipo de categorías"><option value="expense" ${kind==='expense'?'selected':''}>Gastos</option><option value="income" ${kind==='income'?'selected':''}>Ingresos</option></select><input id="category-search" type="search" aria-label="Buscar categorías" placeholder="Buscar por nombre o ruta…" value="${esc(query)}"></div><div class="category-grid">${s.categories.filter(c=>!c.parent&&c.kind===kind&&included(c)).map(c=>branch(c)).join('')||empty('No hay categorías para esta búsqueda.')}</div>`;
}
export function analysis(s,month,kind='expense'){
 const rows=[...s.transactions,...historyRows(s)].filter(t=>t.kind===kind&&t.date.startsWith(month)),total=rows.reduce((n,t)=>n+t.amount,0);const groups=s.categories.filter(c=>c.kind===kind&&!c.parent).map(c=>{const ids=descendants(s,c.id);return {...c,total:rows.filter(t=>ids.has(t.category)).reduce((n,t)=>n+t.amount,0)};}).filter(c=>c.total).sort((a,b)=>b.total-a.total);
 return `<div class="toolbar"><input type="month" id="month" aria-label="Mes" value="${month}"><select id="analysis-kind" aria-label="Tipo de análisis"><option value="expense" ${kind==='expense'?'selected':''}>Gastos</option><option value="income" ${kind==='income'?'selected':''}>Ingresos</option></select></div><section class="card analysis-total"><div class="stacked">${groups.map(c=>`<i style="background:${color(c.color)};flex:${c.total}"></i>`).join('')}</div><strong>${money(total)}</strong><small>${rows.length} movimientos · ${month}</small></section><h2>Categorías</h2><div class="analysis-list">${groups.map(c=>`<details class="card" data-open="analysis:${c.id}"><summary>${icon(c.icon,c.color)}<strong>${esc(c.name)}</strong><span class="percent">${Math.round(c.total/Math.max(total,1)*100)}%</span><b>${money(c.total)}</b></summary><div class="detail">${s.categories.filter(x=>x.parent===c.id).map(x=>{const ids=descendants(s,x.id);const n=rows.filter(t=>ids.has(t.category)).reduce((n,t)=>n+t.amount,0);return n?`<div class="list-row">${icon(x.icon,x.color)}<div>${esc(x.name)}</div><b>${money(n)}</b></div>`:'';}).join('')}</div></details>`).join('')||empty('No hay movimientos en este período.')}</div>`;
}
export function calendar(s,month,selected){const [year,m]=month.split('-').map(Number),offset=(new Date(year,m-1,1).getDay()+6)%7,days=new Date(year,m,0).getDate();const pending=dueItems(s,month+'-'+days);return `<div class="toolbar"><input id="month" aria-label="Mes" type="month" value="${month}"></div><section class="card"><div class="calendar-grid">${['L','M','M','J','V','S','D'].map(x=>`<small>${x}</small>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),rows=s.transactions.filter(t=>t.date===date),due=pending.filter(t=>t.date===date);return `<button class="calendar-day ${selected===date?'active':''} ${date===today()?'today':''}" data-action="calendar-day" data-date="${date}"><b>${i+1}</b><span>${rows.length?'<i class="activity"></i>':''}${due.length?'<i class="planned"></i>':''}</span></button>`;}).join('')}</div><p class="muted">● Movimientos · <span class="positive">● Próximos vencimientos</span></p></section>${selected?`<section class="card"><h2>${selected}</h2>${s.transactions.filter(t=>t.date===selected).map(t=>`<div class="list-row"><div>${esc(t.description||categoryPath(s,t.category))}</div><b>${money(t.amount)}</b>${edit('transactions',t.id)}</div>`).join('')||empty('Sin movimientos registrados.')}${pending.filter(t=>t.date===selected).map(t=>`<div class="list-row"><div><strong>${esc(t.description||'Vencimiento')}</strong><small>Pendiente</small></div>${money(t.amount)}</div>`).join('')}</section>`:''}`;}
export function planningCards(s,key){const installments=key==='installments',rows=s[key],due=dueItems(s,today()).filter(x=>x.sourceType===key);return `<div class="toolbar">${add(key,installments?'Compra en cuotas':'Recurrente')}<button data-action="register-due">Registrar vencimientos hasta hoy (${due.length})</button></div><div class="grid">${rows.map(r=>`<details class="card" data-open="${key}:${r.id}"><summary>${icon(installments?'card':'transfer')}<strong>${esc(r.description||'Sin descripción')}</strong><b>${money(installments?r.total:r.amount)}</b>${edit(key,r.id)}</summary><div class="detail"><p>${esc(s.accounts.find(a=>a.id===r.account)?.name)} · ${esc(categoryPath(s,r.category))}</p><p>${installments?`${r.count} cuotas · ${r.next_number-1} registradas · Primera ${r.first_date}`:`Próxima: ${r.next_date} · ${esc(({daily:'Diaria',weekly:'Semanal',monthly:'Mensual',yearly:'Anual'})[r.frequency])}`}</p><span class="badge">${r.active?'Activo':'Finalizado / pausado'}</span><p>${esc(r.note||'')}</p></div></details>`).join('')||empty('Todavía no hay registros.')}</div>`;}
export function budgetCards(s,month){return `<div class="toolbar">${add('budgets','Presupuesto')}<input id="month" aria-label="Mes" type="month" value="${month}"></div><div class="grid">${s.budgets.map(b=>{const ids=b.category?descendants(s,b.category):null;const spent=s.transactions.filter(t=>t.kind==='expense'&&t.date.startsWith(month)&&(!b.account||t.account===b.account)&&(!ids||ids.has(t.category))).reduce((n,t)=>n+t.amount,0);return `<section class="card"><div class="row"><h2>${esc(b.name)}</h2>${edit('budgets',b.id)}</div><strong>${money(spent)} / ${money(b.amount)}</strong><div class="bar"><i style="width:${Math.min(100,spent/b.amount*100)}%"></i></div><p>${money(b.amount-spent)} disponibles</p></section>`;}).join('')||empty('Creá un presupuesto mensual.')}</div>`;}
export function tools(){return `<div class="grid tool-grid">${[['work','Viajes','route','Recorridos, extras y kilometraje'],['flex','Flex','pin','Envíos y tarifas por zona'],['budgets','Presupuestos','chart','Seguimiento de tus límites mensuales']].map(([v,t,i,sub])=>`<button class="card tool-card" data-view="${v}">${icon(i)}<h2>${t}</h2><p>${sub}</p><span>Ver herramienta →</span></button>`).join('')}</div>`;}
export function more(){return `<div class="more-grid">${pages.filter(([v])=>!['home','transactions','tools'].includes(v)).map(([v,t,i])=>nav(v,t,i)).join('')}</div>`;}
export function review(s){return `<div class="toolbar"><button class="primary" data-action="scan">Escanear comprobante</button></div><div class="grid">${s.review.map(r=>`<article class="card"><div class="row">${icon('receipt')}<strong>${esc(r.description||'Comprobante')}</strong><b>${money(r.amount||0)}</b></div><p>${esc(r.date)}</p><div class="toolbar"><button data-action="review-edit" data-id="${esc(r.id)}">Revisar y registrar</button><button class="danger" data-action="review-remove" data-id="${esc(r.id)}">Descartar</button></div></article>`).join('')||empty('No hay comprobantes pendientes.')}</div>`;}
export function visualFields(r){return `<section class="appearance-editor"><div class="icon-preview">${icon(r.icon||'wallet',r.color)}<div><strong>Identidad visual</strong><small>Elegí un icono y su color</small></div></div><div class="appearance-fields"><label>Color<input type="color" name="color" value="${color(r.color)}"></label><label>Icono<select name="icon">${iconCatalog.map(([k,t])=>`<option value="${k}" ${k===(r.icon||'wallet')?'selected':''}>${esc(t)}</option>`).join('')}</select></label></div><div class="color-options">${palette.map(c=>`<button type="button" data-color="${c}" aria-label="Color ${c}" aria-pressed="${color(r.color).toUpperCase()===c.toUpperCase()}" style="--swatch:${c}"></button>`).join('')}</div><details class="icon-catalog"><summary>Explorar iconos (${iconCatalog.length})</summary><label>Buscar icono<input type="search" class="icon-search" placeholder="Casa, cerebro, tarjeta…"></label><div class="icon-options">${iconCatalog.map(([k,t])=>`<button type="button" data-icon="${k}" data-label="${esc(t)}" aria-label="${esc(t)}" aria-pressed="${k===(r.icon||'wallet')}">${icon(k,r.color)}<small>${esc(t)}</small></button>`).join('')}</div></details></section>`;}
export function bindVisualFields(root){
 const section=root.querySelector('.appearance-editor');if(!section)return;
 const choice=section.querySelector('[name=icon]'),accent=section.querySelector('[name=color]');
 const refresh=()=>{section.querySelector('.icon-preview .illustrated').outerHTML=icon(choice.value,accent.value);section.querySelectorAll('[data-icon]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.icon===choice.value);b.querySelector('.illustrated').outerHTML=icon(b.dataset.icon,accent.value);});section.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.color.toUpperCase()===accent.value.toUpperCase()));};
 choice.addEventListener('change',refresh);accent.addEventListener('input',refresh);
 section.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.icon)choice.value=b.dataset.icon;if(b?.dataset.color)accent.value=b.dataset.color;if(b)refresh();});
 section.querySelector('.icon-search').addEventListener('input',e=>{const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=normalize(e.target.value);section.querySelectorAll('[data-icon]').forEach(b=>b.hidden=!normalize(b.dataset.label+' '+b.dataset.icon+' '+(({brain:'cerebro psicologo',dumbbell:'gimnasio',wifi:'wifi',coins:'efectivo dinero','piggy-bank':'ahorros'})[b.dataset.icon]||'')).includes(q));});
}
