import {fresh,validate} from './model.mjs';
const request = r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
let connection;
let workspace='state';
export function useWorkspace(user){workspace=user?'user:'+user:'state';}
export function currentWorkspace(){return workspace;}
async function open(){if(connection)return connection;const r=indexedDB.open('app-gastos-independent',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');connection=await request(r);connection.onversionchange=()=>{connection.close();connection=null;};return connection;}
export async function read(){const key=workspace,db=await open();const result=await request(db.transaction('data').objectStore('data').get(key));return result?validate(result):fresh();}
export async function mutate(fn){const key=workspace,db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');const store=tx.objectStore('data');let result;const r=store.get(key);r.onsuccess=()=>{try{result=validate(fn(r.result||fresh()));store.put(result,key);}catch(e){reject(e);tx.abort();}};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('No se guardó el cambio.'));});}
export async function localValue(key,value){const db=await open();if(arguments.length===1)return request(db.transaction('data').objectStore('data').get(key));return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=()=>resolve(value);tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error);});}
// State and sync base advance in the same transaction, including edits made offline.
export async function syncTransaction(fn){const key=workspace;if(key==='state')throw Error('Elegí una cuenta.');const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite'),store=tx.objectStore('data');let state,meta,result,count=0;const ready=()=>{if(++count!==2)return;try{result=fn?.({state:state||fresh(),meta:meta||{}});if(result){store.put(validate(result.state),key);store.put(result.meta,key+':sync');}}catch(e){reject(e);tx.abort();}};const a=store.get(key),b=store.get(key+':sync');a.onsuccess=()=>{state=a.result;ready();};b.onsuccess=()=>{meta=b.result;ready();};tx.oncomplete=()=>resolve(result||{state:state||fresh(),meta:meta||{}});tx.onabort=()=>reject(tx.error||Error('No se pudo aplicar la sincronización.'));});}
