import {esc,icon,money} from './desktop-ui.mjs';
import {categoryPath,descendants} from './planning.mjs';
export const normalize=text=>String(text??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterTransactions(s,f){
 const ids=f.category?descendants(s,f.category):null;
 return s.transactions.filter(t=>(!f.month||t.date.startsWith(f.month))&&(!f.from||t.date>=f.from)&&(!f.until||t.date<=f.until)&&(!f.kind||f.kind==='all'||t.kind===f.kind)&&(!f.account||t.account===f.account||t.to===f.account)&&(!ids||ids.has(t.category))&&(!f.min||t.amount>=f.min)&&(!f.max||t.amount<=f.max)&&normalize([t.description,t.note,t.tags,categoryPath(s,t.category),s.accounts.find(a=>a.id===t.account)?.name,s.accounts.find(a=>a.id===t.to)?.name].join(' ')).includes(normalize(f.query)))
 .sort((a,b)=>f.sort==='amount-desc'?b.amount-a.amount||b.date.localeCompare(a.date):f.sort==='amount-asc'?a.amount-b.amount||b.date.localeCompare(a.date):f.sort==='oldest'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));
}
const option=(k,t,v)=>`<option value="${esc(k)}" ${k===v?'selected':''}>${esc(t)}</option>`;
export function transactionScreen(s,f,limit=50){
 const rows=filterTransactions(s,f),income=rows.filter(t=>t.kind==='income').reduce((n,t)=>n+t.amount,0),expense=rows.filter(t=>t.kind==='expense').reduce((n,t)=>n+t.amount,0),advanced=f.category||f.from||f.until||f.min||f.max||!f.month;
 return `<div class="filter-strip"><input id="tx-search" type="search" aria-label="Buscar movimientos" placeholder="Descripción, categoría, cuenta o nota…" value="${esc(f.query)}"><select id="tx-kind" aria-label="Tipo de movimientos">${[['all','Todos'],['expense','Gastos'],['income','Ingresos'],['transfer','Transferencias']].map(([k,t])=>option(k,t,f.kind)).join('')}</select><select id="tx-account" aria-label="Filtrar por cuenta">${option('','Todas las cuentas',f.account)}${s.accounts.map(a=>option(a.id,a.name,f.account)).join('')}</select></div>
 <details class="filter-panel card" data-open="transaction-filters" ${advanced?'open':''}><summary>Más filtros ${advanced?'· activos':''}</summary><div class="filter-fields"><label>Período<select id="tx-all"><option value="month" ${f.month?'selected':''}>Mes seleccionado</option><option value="all" ${!f.month?'selected':''}>Todo el historial</option></select></label><label>Categoría y subcategorías<select id="tx-category">${option('','Todas',f.category)}${s.categories.map(c=>option(c.id,categoryPath(s,c.id),f.category)).join('')}</select></label><label>Desde<input id="tx-from" type="date" value="${esc(f.from)}"></label><label>Hasta<input id="tx-until" type="date" value="${esc(f.until)}"></label><label>Importe mínimo<input id="tx-min" inputmode="decimal" type="number" min="0" step="0.01" value="${f.min?f.min/100:''}"></label><label>Importe máximo<input id="tx-max" inputmode="decimal" type="number" min="0" step="0.01" value="${f.max?f.max/100:''}"></label></div><button class="quiet" data-action="tx-reset">Limpiar filtros</button></details>
 <div class="tx-results"><span>${rows.length} movimientos</span><span class="positive">Ingresos ${money(income)}</span><span class="negative">Gastos ${money(expense)}</span></div><div class="toolbar"><select id="tx-sort" aria-label="Ordenar movimientos">${[['newest','Más recientes'],['oldest','Más antiguos'],['amount-desc','Mayor importe'],['amount-asc','Menor importe']].map(([k,t])=>option(k,t,f.sort)).join('')}</select></div>
 <div class="transaction-cards">${rows.slice(0,limit).map(t=>{const c=s.categories.find(c=>c.id===t.category),account=s.accounts.find(a=>a.id===t.account),destination=s.accounts.find(a=>a.id===t.to),kind=({expense:'Gasto',income:'Ingreso',transfer:'Transferencia'})[t.kind];return `<details class="card transaction-card" data-open="transaction:${esc(t.id)}"><summary>${icon(t.kind==='transfer'?'transfer':c?.icon||'receipt',c?.color)}<span class="transaction-heading"><strong>${esc(t.description||c?.name||kind)}</strong><small>${esc(t.date)} · ${esc(account?.name||'Sin cuenta')}</small></span><b class="${t.kind==='expense'?'negative':t.kind==='income'?'positive':''}">${t.kind==='expense'?'−':t.kind==='income'?'+':''}${money(t.amount)}</b></summary><div class="detail"><dl><dt>Tipo</dt><dd>${kind}</dd><dt>${t.kind==='transfer'?'Destino':'Categoría'}</dt><dd>${esc(t.kind==='transfer'?destination?.name:categoryPath(s,t.category)||'Sin categoría')}</dd>${t.tags?`<dt>Etiquetas</dt><dd>${esc(t.tags)}</dd>`:''}</dl>${t.note?`<p class="transaction-note">${esc(t.note)}</p>`:''}<div class="toolbar"><button data-action="edit" data-key="transactions" data-id="${esc(t.id)}">Editar</button><button class="quiet" data-action="tx-duplicate" data-id="${esc(t.id)}">Usar como nuevo</button></div></div></details>`;}).join('')||'<p class="empty">No hay movimientos que coincidan. Probá ampliar el período o limpiar los filtros.</p>'}</div>${rows.length>limit?'<button class="load-more" data-action="tx-more">Mostrar 50 más</button>':''}`;
}
