import {icon,esc,money} from './desktop-ui.mjs';
const edit=(key,id)=>`<button class="quiet" data-action="edit" data-key="${key}" data-id="${esc(id)}">Editar</button>`;
const metric=(name,value,sub='')=>`<div class="card metric"><small>${name}</small><strong>${value}</strong>${sub?`<small>${sub}</small>`:''}</div>`;
const badge=text=>`<span class="badge">${text}</span>`;
export function workScreen(s,work,period,month,range,query=''){
 const [start,end]=range,inRange=r=>r.date>=start&&r.date<=end;
 const mileage=s.mileage.filter(inRange),totalKM=mileage.reduce((n,r)=>n+r.end-r.start,0),trips=s.trips.filter(inRange),extras=s.extras.filter(inRange),deliveries=s.deliveries.filter(inRange);
 const rows=(work==='extras'?extras:trips).filter(r=>`${r.client||r.app} ${r.origin||''} ${(r.destinations||[]).join(' ')} ${r.note||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const fields=s.workFields.filter(f=>f.active),count=trips.reduce((n,t)=>n+(t.trip_count||1),0),stops=trips.reduce((n,t)=>n+t.stops,0);
 const controls=`<div class="work-head"><button data-action="work-mode" data-mode="mileage">Kilometraje</button><button class="primary" data-action="work-new">${work==='extras'?'＋ Nuevo extra':work==='deliveries'?'＋ Nueva zona':work==='mileage'?'＋ Kilometraje':'＋ Nuevo viaje'}</button><button data-action="work-config">Personalizar</button></div><div class="toolbar work-period"><select id="period" aria-label="Período"><option value="week" ${period==='week'?'selected':''}>Esta semana</option><option value="month" ${period==='month'?'selected':''}>Este mes</option></select><input id="month" aria-label="Mes" type="month" value="${month}" ${period==='week'?'disabled':''}><span class="muted">${start} — ${end}</span></div>`;
 let metrics=work==='extras'?metric('Horas',extras.reduce((n,r)=>n+r.minutes,0)/60+' h')+metric('Pedidos / viajes',extras.reduce((n,r)=>n+r.orders,0))+metric('Ganado',money(extras.reduce((n,r)=>n+r.amount,0))):metric('Viajes',count,stops+' paradas')+metric('Bulto',trips.filter(r=>r.bulky).length)+metric('Lluvia',trips.filter(r=>r.rain).length)+metric('Flex',trips.filter(r=>r.flex).reduce((n,r)=>n+r.stops,0),'paradas')+metric('Cliente propio',trips.filter(r=>r.own).length)+metric('KM reales',totalKM.toFixed(1)+' km',mileage.length?'Prom. '+(totalKM/mileage.length).toFixed(1)+' km/día · '+mileage.length+' días':'Sin kilometraje')+metric('Cobrado',money(trips.reduce((n,r)=>n+r.amount,0)));
 let content='';
 if(work==='deliveries'){
  metrics=metric('Envíos',deliveries.reduce((n,r)=>n+(r.quantity||1),0))+metric('Total',money(deliveries.reduce((n,r)=>n+r.amount,0)));
  content=`<div class="grid">${s.zones.map(z=>{const rows=deliveries.filter(r=>r.zone===z.id);return `<section class="card"><div class="account-top">${icon('pin',z.color)}<div><h3>${esc(z.name)}</h3><small>Tarifa actual · ${money(z.rate)}</small></div>${edit('zones',z.id)}</div><div class="metrics">${metric('Envíos',rows.reduce((n,r)=>n+(r.quantity||1),0))}${metric('Subtotal',money(rows.reduce((n,r)=>n+r.amount,0)))}</div><div class="toolbar"><button data-action="minus" data-id="${esc(z.id)}">−</button><button class="primary" data-action="delivery" data-id="${esc(z.id)}">＋ 1 Flex</button></div></section>`;}).join('')}</div>`;
 } else if(work==='mileage')content=`<div class="grid">${mileage.map(r=>`<details class="card" data-open="km:${r.id}"><summary><strong>${r.date}</strong><b>${(r.end-r.start).toFixed(1)} km</b>${edit('mileage',r.id)}</summary><p>Odómetro inicial ${r.start} · Final ${r.end}</p></details>`).join('')||'<p class="empty">Sin kilometraje registrado.</p>'}</div>`;
 else {
  const dates=[...new Set([...rows.map(r=>r.date),...mileage.map(r=>r.date)])].sort();
  content=`<div class="filter-strip"><input id="work-search" type="search" aria-label="Buscar viajes" value="${esc(query)}" placeholder="Buscar cliente, origen, destino o comentario…"></div><div class="section-tabs"><button data-action="work-mode" data-mode="trips" class="${work==='trips'?'active':''}">Viajes</button><button data-action="work-mode" data-mode="extras" class="${work==='extras'?'active':''}">Extras</button></div>${dates.map(date=>{const day=rows.filter(r=>r.date===date),km=mileage.find(r=>r.date===date),label=new Date(date+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'2-digit',month:'short'});return `<details class="card day-group" data-open="day:${work}:${date}"><summary><strong>${label.toUpperCase()}</strong><span class="day-badges">${badge(day.length+(work==='extras'?' registros':' viajes'))}${work==='trips'?badge(day.reduce((n,r)=>n+r.stops,0)+' paradas'):badge(day.reduce((n,r)=>n+r.minutes,0)/60+' h')}${km?badge((km.end-km.start).toFixed(1)+' km reales'):''}</span></summary><div class="day-trips">${day.map(r=>`<details class="card" data-open="trip:${r.id}"><summary><strong>${esc(r.client||r.app)}</strong><b>${r.amount?money(r.amount):'<small>Sin importe</small>'}</b>${edit(work,r.id)}</summary><div class="detail">${work==='trips'?`<div class="trip-route"><small>Desde</small><span>${esc(r.origin||'—')}</span><small>${r.stops} paradas</small><span>${esc(r.destinations.join(' → '))}</span></div><div class="trip-flags">${['bulky','rain','flex','own'].map((key,i)=>`<label class="check"><input type="checkbox" data-check="${key}" data-id="${r.id}" ${r[key]?'checked':''}>${['Bulto','Lluvia','Flex','Cliente propio'][i]}</label>`).join('')}</div>${fields.map(f=>`<p><small>${esc(f.name)}</small> ${esc(r.custom?.[f.id]??'—')}</p>`).join('')}`:`<p>${r.minutes/60} horas · ${r.orders} pedidos / viajes</p>`}${r.note?`<p class="muted">${esc(r.note)}</p>`:''}</div></details>`).join('')||'<p class="empty">Sin registros.</p>'}</div></details>`;}).join('')||'<p class="empty">Sin registros en este período.</p>'}`;
 }
 return controls+`<div class="metrics work-metrics">${metrics}</div>`+content;
}
export function workConfiguration(s){return `<div class="toolbar"><button data-view="work">‹ Volver a Viajes</button><button class="primary" data-action="catalog-new" data-key="workFields">＋ Agregar campo</button></div><p class="muted">Los campos aparecen al crear o editar un viaje.</p>${s.workFields.map(f=>`<section class="card field-config"><div><h3>${esc(f.name)}</h3><small>${esc(f.type)} · ${f.active?'Activo':'Oculto'} · ${f.summary?'En resumen':'Solo detalle'}</small></div><div class="toolbar">${edit('workFields',f.id)}</div></section>`).join('')||'<section class="card">Bulto, Lluvia, Flex y Cliente propio ya están disponibles. Agregá campos propios para adaptar tus viajes.</section>'}`;}
