import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fresh} from '../mobile/model.mjs';
import {synchronize,SyncConflict} from '../mobile/sync-engine.mjs';
const make=()=>{const state=fresh();state.extras=[{id:'e',app:'A',date:'2026-01-01',minutes:60,orders:1,amount:100}];let current={state,meta:{enabled:true,base:structuredClone(state)}};return {get:()=>current,tx:async(fn)=>{if(fn)current=fn(structuredClone(current));return structuredClone(current);}};};
test('receives changes and keeps local edits made during network wait',async()=>{const local=make();const remote=structuredClone(local.get().state);remote.extras[0].amount=300;const client={copy:async()=>{local.get().state.extras.push({id:'new',app:'B',date:'2026-01-01',minutes:60,orders:1,amount:150});return {revision:2,document:remote};},save:async()=>{throw Error('should not upload');}};await synchronize({client,transaction:local.tx});assert.equal(local.get().state.extras[0].amount,300);assert.equal(local.get().state.extras.length,2);assert.equal(local.get().meta.base.extras.length,1);});
test('conflict does not write or discard either side',async()=>{const local=make();local.get().state.extras[0].amount=200;const remote=structuredClone(local.get().state);remote.extras[0].amount=300;await assert.rejects(synchronize({client:{copy:async()=>({revision:2,document:remote}),save:()=>assert.fail()},transaction:local.tx}),SyncConflict);assert.equal(local.get().state.extras[0].amount,200);assert.equal(local.get().meta.base.extras[0].amount,100);});
test('lost response is recovered on next read without duplicate writes',async()=>{const local=make();local.get().state.extras[0].amount=200;let stored=structuredClone(local.get().meta.base),saves=0;const client={copy:async()=>({revision:1+saves,document:stored}),save:async(doc)=>{stored=doc;saves++;throw Error('network lost');}};await assert.rejects(synchronize({client,transaction:local.tx,operation:()=> 'op'}));await synchronize({client,transaction:local.tx});assert.equal(saves,1);assert.equal(local.get().meta.base.extras[0].amount,200);});
test('optimistic revision rejection does not advance local base',async()=>{const local=make();local.get().state.extras[0].amount=200;await assert.rejects(synchronize({client:{copy:async()=>({revision:1,document:local.get().meta.base}),save:async()=>({ok:false})},transaction:local.tx}));assert.equal(local.get().meta.base.extras[0].amount,100);});
