const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/nnfao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(process.env.BASE_URL||'http://127.0.0.1:8767/');await page.locator('.dashboard-overview').waitFor();
 await page.evaluate(async()=>{const {mutate}=await import('./storage.mjs');const {today}=await import('./model.mjs');await mutate(s=>{const c=s.categories.find(c=>c.kind==='expense'&&c.parent);s.transactions=[{id:'one',kind:'expense',date:today(),amount:15000,account:'cash',category:c.id,description:'Café con amigos',note:'Nota de prueba'},{id:'old',kind:'expense',date:'2020-01-01',amount:60000,account:'cash',category:c.id,description:'Compra anterior'}];s.workFields=[{id:'field',name:'Propina',type:'number',active:true,summary:true},{id:'flag',name:'Urgente',type:'check',active:true,summary:true}];s.trips=[{id:'trip',client:'Cliente prueba',date:today(),destinations:['Olivos'],origin:'Centro',stops:1,amount:20000,custom:{field:25,flag:false}}];s.zones=[{id:'z',name:'Zona prueba',rate:10000}];s.deliveries=[{id:'batch',zone:'z',date:today(),amount:30000,quantity:3}];return s;});});await page.reload();
 await page.locator('#bottom-nav [data-view=transactions]').click();await page.locator('#tx-search').fill('cafe');await page.waitForTimeout(350);assert.equal(await page.locator('.transaction-card').count(),1);await page.locator('.transaction-card summary').click();await page.getByText('Nota de prueba',{exact:true}).waitFor();await page.locator('[data-action=tx-duplicate]').click();assert.equal(await page.locator('[name=description]').inputValue(),'Café con amigos');await page.locator('#close').click();
 await page.locator('.filter-panel summary').click();await page.locator('#tx-all').selectOption('all');await page.locator('#tx-search').fill('');await page.waitForTimeout(350);assert.equal(await page.locator('.transaction-card').count(),2);await page.locator('#tx-min').fill('200');await page.locator('#tx-min').dispatchEvent('change');assert.equal(await page.locator('.transaction-card').count(),1);await page.getByText('Compra anterior',{exact:true}).waitFor();await page.locator('[data-action=tx-reset]').click();
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`transactions ${width}`);await page.screenshot({path:`build/mobile-transactions-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.locator('#bottom-nav [data-view=tools]').click();await page.locator('[data-view=work]').click();await page.locator('.work-metrics .metric').filter({hasText:'Propina'}).getByText('25',{exact:true}).waitFor();await page.locator('.day-group>summary').click();await page.locator('.day-trips summary').click();await page.locator('[data-custom-check=flag]').check();await page.waitForFunction(async()=>{const {read}=await import('./storage.mjs');return (await read()).trips[0].custom.flag===true;});
 await page.locator('[data-action=work-config]').click();await page.locator('[data-field-toggle=summary][data-id=field]').uncheck();await page.waitForFunction(async()=>{const {read}=await import('./storage.mjs');return (await read()).workFields[0].summary===false;});await page.locator('[data-action=field-move][data-id=field][data-direction="1"]').click();await page.waitForFunction(async()=>{const {read}=await import('./storage.mjs');return (await read()).workFields[1].id==='field';});
 await page.locator('#bottom-nav [data-view=tools]').click();await page.locator('[data-view=flex]').click();await page.locator('[data-action=minus]').click();await page.waitForFunction(async()=>{const {read}=await import('./storage.mjs');return (await read()).deliveries[0].quantity===2;});await page.locator('[data-action=delivery]').click();await page.waitForFunction(async()=>{const {read}=await import('./storage.mjs');return (await read()).deliveries.length===2;});
 assert.deepEqual(errors,[]);console.log('MOBILE_FILTERS_CUSTOM_FIELDS_FLEX_OK');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
