const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/nnfao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(process.env.BASE_URL||'http://127.0.0.1:8767/');await page.getByRole('button',{name:'＋ Movimiento',exact:true}).waitFor();
  const go=async v=>{if(page.viewportSize().width>=1000){await page.locator(`#sidebar [data-view="${v}"]`).click();}else if(['home','transactions','tools'].includes(v)){await page.locator(`#bottom-nav [data-view="${v}"]`).click();}else{await page.locator('#bottom-nav [data-view=more]').click();await page.locator(`#content [data-view="${v}"]`).click();}};
  await go('recurring');await page.locator('[data-key=recurring][data-action=catalog-new]').click();await page.locator('[name=amount]').fill('1200');await page.locator('[name=description]').fill('Alquiler recurrente');await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);await page.locator('[data-action=register-due]').click();
  await go('installments');await page.locator('[data-key=installments][data-action=catalog-new]').click();await page.locator('[name=total]').fill('100');await page.locator('[name=description]').fill('Compra de prueba');await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
  await go('categories');await page.locator('.category-node summary').first().click();const child=page.locator('[data-action=category-up]').first(),childID=await child.getAttribute('data-id');await child.click();assert.equal(await page.locator(`.category-node[data-open="category:${childID}"]`).count(),1);
  await go('accounts');await page.locator('[data-action=edit]').first().click();await page.locator('[name=type]').selectOption('Ahorro');await page.locator('[name=icon]').selectOption('piggy-bank');await page.locator('[name=include]').uncheck();await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);await page.getByText('Separada',{exact:true}).waitFor();
  await go('tools');await page.locator('[data-view=work]').click();await page.locator('[data-action=work-config]').click();await page.locator('[data-key=workFields][data-action=catalog-new]').click();await page.locator('[name=name]').fill('Referencia');await page.locator('[name=type]').selectOption('text');await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);
  for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});for(const v of ['home','transactions','calendar','review','accounts','installments','stats','categories','recurring','tools','settings']){await go(v);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width} ${v}`);assert(!await page.getByText('undefined',{exact:true}).count(),v);}await go('categories');await page.screenshot({path:`build/mobile-categories-${width}.png`,fullPage:true});}
  assert.deepEqual(errors,[]);console.log('DESKTOP_MOBILE_SCREENS_AND_FORMS_OK');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
