const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/nnfao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(process.env.BASE_URL||'http://127.0.0.1:8767/');await page.locator('.dashboard-overview').waitFor();
 await page.evaluate(async()=>{const {mutate}=await import('./storage.mjs'),{today}=await import('./model.mjs');await mutate(s=>{s.accounts.push({id:'saving',name:'Ahorros',type:'Ahorro',initial:15200000,include:false,icon:'piggy-bank',color:'#985CF3'});s.transactions.push({id:'salary',kind:'income',amount:95000000,account:'cash',date:today(),description:'Ingreso de prueba',category:s.categories.find(c=>c.kind==='income').id},{id:'expense',kind:'expense',amount:12000000,account:'cash',date:today(),description:'Compra de prueba',category:s.categories.find(c=>c.kind==='expense'&&c.parent).id});return s;});});await page.reload();await page.locator('.donut').waitFor();
 const original=await page.locator('#month').inputValue();await page.locator('[data-action=period-prev]').click();assert.notEqual(await page.locator('#month').inputValue(),original);await page.locator('[data-action=period-next]').click();assert.equal(await page.locator('#month').inputValue(),original);
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`build/mobile-dashboard-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.locator('.wallet-mini').first().click();assert(await page.locator('[name=credit_limit]').isHidden());await page.locator('[name=type]').selectOption('Tarjeta');assert(await page.locator('[name=credit_limit]').isVisible());await page.locator('.icon-catalog summary').click();await page.locator('.icon-search').fill('cerebro');await page.locator('[data-icon=brain]').click();assert.equal(await page.locator('[name=icon]').inputValue(),'brain');await page.locator('[data-color]').first().click();assert.equal(await page.locator('[name=color]').inputValue(),'#29a6aa');await page.locator('#close').click();
 await page.locator('#bottom-nav [data-view=tools]').click();await page.locator('[data-view=work]').click();await page.locator('[data-action=work-period][data-period=week]').click();await page.locator('#work-date').fill('2026-01-01');await page.locator('#work-date').dispatchEvent('change');assert.match(await page.locator('.period-label span').innerText(),/29.*dic.*04.*ene.*2026/i);await page.locator('[data-action=period-prev]').click();assert.equal(await page.locator('#work-date').inputValue(),'2025-12-25');
 await page.locator('[data-action=work-mode][data-mode=mileage]').click();await page.locator('.tool-navigation [data-view=work]').click();await page.locator('[data-action=work-mode][data-mode=extras]').waitFor();
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`work overflow ${width}`);}
 assert.deepEqual(errors,[]);console.log('DASHBOARD_PERIODS_ICON_PICKER_OK');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

