const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const monthsShort=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const state={
  token:localStorage.getItem('ag_token')||'', data:null, view:'home', stack:[], year:new Date().getFullYear(),month:new Date().getMonth()+1,
  txYear:new Date().getFullYear(),txMonth:new Date().getMonth()+1,txKind:'all',txSearch:'',txRange:null,txCategory:null,
  editTxId:null,txFormKind:'expense',txCategoryId:null,categoryCallback:null,
  analysisKind:'expense',analysisMode:'month',analysisAnchor:new Date(),analysisData:null,
  flexWeek:mondayISO(new Date()), categoriesKind:'expense', reviewSource:'', scanConfig:null,
  calYear:new Date().getFullYear(),calMonth:new Date().getMonth()+1
};
const ICONS={
  home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',
  transactions:'<path d="M7 7h12"/><path d="m15 3 4 4-4 4"/><path d="M17 17H5"/><path d="m9 13-4 4 4 4"/>',
  chart:'<path d="M4 20V10"/><path d="M10 20V4"/><path d="M16 20v-7"/><path d="M22 20H2"/>',
  more:'<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>',
  back:'<path d="m15 18-6-6 6-6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',sync:'<path d="M20 7h-5V2"/><path d="M20 7a8 8 0 1 0 2 5"/>',
  left:'<path d="m15 18-6-6 6-6"/>',right:'<path d="m9 18 6-6-6-6"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
  wallet:'<path d="M4 6.5h15a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2v-12a2 2 0 0 1 2-2h13"/><path d="M16 11h5v4h-5a2 2 0 1 1 0-4Z"/>',
  card:'<rect x="2.5" y="5" width="19" height="14" rx="2.5"/><path d="M2.5 9h19M6 15h4"/>',
  bank:'<path d="m3 9 9-5 9 5"/><path d="M5 10v7M9.5 10v7M14.5 10v7M19 10v7M3 20h18"/>',
  cash:'<rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M6 9h.01M18 15h.01"/>',
  savings:'<path d="M5 9c2-3 12-3 14 0v8c-2 3-12 3-14 0Z"/><path d="M8 7V4h8v3M12 11v4M10 13h4"/>',
  installments:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 9h10M7 13h6M7 17h3"/>',
  package:'<path d="m4 7 8-4 8 4-8 4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>',
  inbox:'<path d="M4 4h16l2 11h-6l-2 3h-4l-2-3H2Z"/><path d="M8 9h8"/>',
  categories:'<path d="M4 4h6v6H4ZM14 4h6v6h-6ZM4 14h6v6H4ZM14 14h6v6h-6Z"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/>',
  edit:'<path d="m4 20 4.5-1 10-10-3.5-3.5-10 10Z"/><path d="m13.8 6.7 3.5 3.5"/>',delete:'<path d="M4 7h16M9 3h6l1 4H8ZM7 7l1 14h8l1-14"/>',
  duplicate:'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>',check:'<path d="m5 12 4 4L19 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',
  food:'<path d="M7 3v7M4 3v5a3 3 0 0 0 6 0V3M17 3v18M17 3c3 3 3 7 0 9"/>',homecat:'<path d="m3 11 9-7 9 7v9H5v-9"/><path d="M9 20v-6h6v6"/>',
  car:'<path d="m5 16-1-4 2-5h12l2 5-1 4"/><path d="M5 16h14v3H5ZM7 12h.01M17 12h.01"/>',fuel:'<path d="M5 21V4h9v17M5 8h9M14 7h3l2 3v7a2 2 0 0 0 2 2"/>',
  health:'<path d="M12 21S4 16 4 9a4 4 0 0 1 7-2.6A4 4 0 0 1 18 9c0 7-6 12-6 12Z"/><path d="M9 12h6M12 9v6"/>',
  education:'<path d="m3 9 9-5 9 5-9 5Z"/><path d="M7 12v4c3 2 7 2 10 0v-4"/>',entertainment:'<path d="M5 6h14v12H5Z"/><path d="m10 9 5 3-5 3Z"/>',
  subscription:'<path d="M7 7h10v10H7Z"/><path d="M4 12h3M17 12h3M12 4v3M12 17v3"/>',gift:'<path d="M4 10h16v11H4ZM3 7h18v3H3ZM12 7v14M12 7H8a2 2 0 1 1 2-3c1 1 2 3 2 3ZM12 7h4a2 2 0 1 0-2-3c-1 1-2 3-2 3Z"/>',
  shopping:'<path d="M5 8h14l-1 12H6ZM9 8a3 3 0 0 1 6 0"/>',person:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',tag:'<path d="M3 12V4h8l10 10-7 7Z"/><circle cx="7.5" cy="8" r="1"/>',
  transfer:'<path d="M4 8h14M15 5l3 3-3 3M20 16H6M9 13l-3 3 3 3"/>',income:'<path d="M12 3v16M6 13l6 6 6-6"/>',expense:'<path d="M12 21V5M6 11l6-6 6 6"/>'
};
function svgIcon(name,cls=''){let n=String(name||'tag').toLowerCase();const aliases={other:'tag',motorcycle:'car',moto:'car',combustible:'fuel',restaurant:'food',comida:'food',house:'homecat',home:'homecat',medical:'health',book:'education',school:'education',game:'entertainment',youtube:'subscription',spotify:'subscription',apple:'subscription',google:'subscription',clothes:'shopping',hygiene:'shopping',money:'cash',salary:'income',work:'person',client:'person',clients:'person',toll:'car',service:'car',insurance:'card'};n=aliases[n]||n;const p=ICONS[n]||ICONS.tag;return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`}
function injectStaticIcons(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svgIcon(el.dataset.icon));$('#backButton').innerHTML=svgIcon('back');$('#syncButton').innerHTML=svgIcon('sync');$$('.period-arrow').forEach((el,i)=>el.innerHTML=svgIcon(i%2===0?'left':'right'));$$('.close').forEach(el=>el.innerHTML=svgIcon('close'));$('#searchIcon').innerHTML=svgIcon('search')}
function money(v){const n=Number(v||0),sign=n<0?'-':'';return `${sign}$ ${Math.abs(n).toLocaleString('es-AR',{minimumFractionDigits:0,maximumFractionDigits:2})}`}
function num(v){return Number(v||0)}
function isoLocal(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function mondayISO(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return isoLocal(x)}
function parseISO(s){const [y,m,d]=String(s).slice(0,10).split('-').map(Number);return new Date(y,m-1,d,12)}
function addDaysISO(s,n){const d=parseISO(s);d.setDate(d.getDate()+n);return isoLocal(d)}
function shiftMonthDate(d,n){const x=new Date(d.getFullYear(),d.getMonth()+n,1,12);return x}
function shortDate(s){if(!s)return'';const [y,m,d]=String(s).slice(0,10).split('-');return `${d}/${m}`}
function longDate(s){if(!s)return'';return parseISO(s).toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escAttr(s){return esc(s).replace(/`/g,'&#96;')}
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
function toast(msg,ms=1800){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),ms)}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(state.token)headers['X-AppGastos-Token']=state.token;const r=await fetch(path,{...opts,headers});const j=await r.json().catch(()=>({ok:false,error:'Respuesta inválida'}));if(r.status===401){unpair();throw new Error('Volvé a vincular este teléfono.')}if(!r.ok||j.ok===false)throw new Error(j.error||'Error');return j}
function unpair(){state.token='';localStorage.removeItem('ag_token');show('#app',false);show('#pairScreen',true)}
async function pair(){const code=$('#pairCode').value.replace(/\D/g,'').slice(0,6);$('#pairError').textContent='';try{const j=await api('/api/pair',{method:'POST',body:JSON.stringify({code})});state.token=j.token;localStorage.setItem('ag_token',state.token);show('#pairScreen',false);show('#app',true);await refreshBootstrap();navigate('home',false)}catch(e){$('#pairError').textContent=e.message}}

function setHeader(){const child=['accounts','installments','flex','review','categories','calendar'].includes(state.view);show('#backButton',child);if(state.view==='home'&&state.data){$('#topEyebrow').textContent='SALDO DISPONIBLE';$('#topTitle').textContent=money(state.data.summary.available_balance)}else{const titles={transactions:['HISTORIAL','Movimientos'],analysis:['TENDENCIAS','Análisis'],more:['APP GASTOS','Más'],accounts:['PATRIMONIO','Cuentas'],installments:['PLANIFICACIÓN','Cuotas'],flex:['MERCADO LIBRE','Flex'],review:['AUTOMATIZACIÓN','Por revisar'],categories:['ORGANIZACIÓN','Categorías'],calendar:['CALENDARIO','Actividad']};const x=titles[state.view]||['APP GASTOS','App Gastos'];$('#topEyebrow').textContent=x[0];$('#topTitle').textContent=x[1]}}
function navigate(view,push=true){if(push&&state.view!==view&&['accounts','installments','flex','review','categories','calendar'].includes(view))state.stack.push(state.view);state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));setHeader();loadView(view);window.scrollTo({top:0,behavior:'instant'})}
function goBack(){navigate(state.stack.pop()||'more',false)}
async function loadView(v){if(v==='home')return refreshBootstrap();if(v==='transactions')return loadTransactions();if(v==='analysis')return loadAnalysis();if(v==='accounts')return loadAccounts();if(v==='installments')return loadInstallments();if(v==='flex')return loadFlex();if(v==='review')return loadReview();if(v==='categories')return loadCategories();if(v==='calendar')return loadCalendar()}

async function refreshBootstrap(){try{const d=await api(`/api/bootstrap?year=${state.year}&month=${state.month}`);state.data=d;renderHome();setHeader();updateMoreBadges()}catch(e){toast(e.message)}}
function renderHome(){const d=state.data;if(!d)return;$('#income').textContent=money(d.summary.income);$('#expense').textContent=money(d.summary.expense);$('#net').textContent=money(d.summary.net);$('#net').className=d.summary.net<0?'negative':'positive';$('#periodLabel').textContent=`${months[state.month-1]} ${state.year}`;renderCategoryBars(d.expense_categories||[]);renderTxList('#recentList',d.recent||[],true);renderHomeInstallments(d.installments);fillAccountSelects(d.accounts||[]);updateMoreBadges()}
function renderHomeInstallments(data){const el=$('#homeInstallments');const cur=data?.current;if(!cur||!cur.count){el.innerHTML='<div class="empty">No tenés cuotas para este mes.</div>';return}const next=data.next||{};el.innerHTML=`<div class="tx" data-open-installments><div class="tx-icon" style="--c:var(--mint)">${svgIcon('installments')}</div><div class="tx-body"><div class="tx-title">${cur.count} cuotas este mes</div><div class="tx-meta">Próximo mes ${next.count||0} · ${money(next.total||0)}</div></div><div class="tx-amount">${money(cur.total)}</div></div>`;el.querySelector('[data-open-installments]').onclick=()=>navigate('installments')}
function renderCategoryBars(rows){const el=$('#categoryBars');if(!rows.length){el.innerHTML='<div class="empty">Todavía no hay gastos en este período.</div>';return}const max=Math.max(...rows.map(x=>num(x.total)),1);el.innerHTML=rows.map(x=>`<div class="cat-row" data-cat="${x.id||''}"><div class="cat-top"><span class="cat-mark" style="--c:${x.color}">${svgIcon(x.icon)}</span><span class="cat-name">${esc(x.name)}</span><b class="cat-amount">${money(x.total)}</b></div><div class="bar"><span style="width:${Math.max(3,num(x.total)/max*100)}%;background:${x.color}"></span></div></div>`).join('');[...el.querySelectorAll('.cat-row')].forEach(r=>r.onclick=()=>{state.analysisKind='expense';state.analysisMode='month';state.analysisAnchor=new Date(state.year,state.month-1,1,12);navigate('analysis');setTimeout(()=>openAnalysisCategory(Number(r.dataset.cat)),80)})}
function txHTML(t,clickable=true){const cls=t.kind==='income'?'income':t.kind==='expense'?'expense':'';const prefix=t.kind==='expense'?'-':t.kind==='income'?'+':'';const icon=t.kind==='income'?'income':t.kind==='expense'?(t.category_icon||'expense'):'transfer';const meta=t.kind==='transfer'?`${esc(t.account_name)} → ${esc(t.to_account_name)} · ${shortDate(t.tx_date)}`:`${esc(t.category||'')} · ${esc(t.account_name||'')} · ${shortDate(t.tx_date)}`;return `<div class="tx" ${clickable?`data-tx="${t.id}"`:''}><div class="tx-icon" style="--c:${t.category_color||'#63DAB7'}">${svgIcon(icon)}</div><div class="tx-body"><div class="tx-title">${esc(t.display||'Movimiento')}</div><div class="tx-meta">${meta}${t.installment_total?` · ${t.installment_number}/${t.installment_total}`:''}</div></div><div class="tx-amount ${cls}">${prefix}${money(t.amount)}</div></div>`}
function renderTxList(sel,rows,bind=false){const el=$(sel);el.innerHTML=rows.length?rows.map(t=>txHTML(t,true)).join(''):'<div class="empty">No hay movimientos todavía.</div>';if(bind||sel==='#allTransactions')el.querySelectorAll('[data-tx]').forEach(r=>r.onclick=()=>openTransaction(Number(r.dataset.tx)))}
function updateMoreBadges(){const n=state.data?.pending?.all||0;$('#reviewTileText').textContent=n?`${n} movimientos pendientes`:'Todo al día';$('#pendingBadge').textContent=n;show('#pendingBadge',n>0)}
function fillAccountSelects(rows){['#accountSelect','#toAccountSelect'].forEach(sel=>{const s=$(sel);const prev=s.value;s.innerHTML=rows.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');if([...s.options].some(o=>o.value===prev))s.value=prev});toggleInstallmentsField()}

async function loadTransactions(){try{const q=new URLSearchParams({limit:'240',kind:state.txKind});if(state.txRange){q.set('from',state.txRange.from);q.set('to',state.txRange.to)}else{q.set('year',state.txYear);q.set('month',state.txMonth)}if(state.txSearch)q.set('search',state.txSearch);if(state.txCategory)q.set('category_id',state.txCategory);const j=await api('/api/transactions?'+q);renderTxList('#allTransactions',j.transactions||[]);$('#txCount').textContent=`${(j.transactions||[]).length} movimientos`;$('#txPeriodLabel').textContent=`${months[state.txMonth-1]} ${state.txYear}`;show('#txRangeBanner',!!state.txRange);if(state.txRange)$('#txRangeLabel').textContent=`${longDate(state.txRange.from)} – ${longDate(state.txRange.to)}`;const h=j.history||[];show('#historyTransactions',h.length>0);if(h.length){$('#historyTransactions').innerHTML=`<div class="history-head"><b>Historial importado</b><span>Totales mensuales del Excel</span></div><div class="glass-card">${h.map(x=>`<div class="history-row"><div class="tx-icon" style="--c:${x.category_color}">${svgIcon(x.category_icon)}</div><div class="tx-body"><div class="tx-title">${esc(x.display)}</div><small>Dato mensual · ${esc(x.file_name||'Excel')}</small></div><div class="tx-amount ${x.kind==='expense'?'expense':'income'}">${x.kind==='expense'?'-':'+'}${money(x.amount)}</div></div>`).join('')}</div>`}}catch(e){toast(e.message)}}
async function openTransaction(id){try{const {transaction:t}=await api(`/api/transaction?id=${id}`);$('#detailTitle').textContent='Movimiento';$('#detailBody').innerHTML=`<div class="detail-hero"><div class="big-icon">${svgIcon(t.kind==='transfer'?'transfer':t.category_icon)}</div><h3>${esc(t.display)}</h3><p>${esc(t.category)} · ${longDate(t.tx_date)}</p><strong class="${t.kind==='expense'?'negative':t.kind==='income'?'positive':''}">${t.kind==='expense'?'-':t.kind==='income'?'+':''}${money(t.amount)}</strong></div><div class="detail-grid"><div class="detail-stat"><span>Cuenta</span><b>${esc(t.account_name)}</b></div><div class="detail-stat"><span>Origen</span><b>${esc(t.source||'manual')}</b></div>${t.installment_total?`<div class="detail-stat"><span>Cuota</span><b>${t.installment_number}/${t.installment_total}</b></div>`:''}<div class="detail-stat"><span>Fecha</span><b>${longDate(t.tx_date)}</b></div></div>${t.note?`<p class="muted">${esc(t.note)}</p>`:''}<div class="detail-actions"><button id="editTx" class="soft-button">Editar</button><button id="dupTx" class="soft-button">Duplicar</button><button id="delTx" class="ghost-danger wide">Eliminar movimiento</button></div>`;openDetail();$('#editTx').onclick=()=>{closeDetail();openMovement(t)};$('#dupTx').onclick=async()=>{try{await api('/api/transactions/duplicate',{method:'POST',body:JSON.stringify({id:t.id,tx_date:isoLocal(new Date())})});closeDetail();toast('Movimiento duplicado');loadTransactions();refreshBootstrap()}catch(e){toast(e.message)}};$('#delTx').onclick=async()=>{if(!confirm('¿Eliminar este movimiento?'))return;try{await api(`/api/transactions?id=${t.id}`,{method:'DELETE'});closeDetail();toast('Movimiento eliminado');loadTransactions();refreshBootstrap()}catch(e){toast(e.message)}}}catch(e){toast(e.message)}}
function clearTxRange(){state.txRange=null;state.txCategory=null;loadTransactions()}

function openMovement(t=null,preset={}){state.editTxId=t?.id||null;state.txFormKind=t?.kind||preset.kind||'expense';state.txCategoryId=t?.category_id||preset.category_id||null;$('#movementSheetTitle').textContent=t?'Editar movimiento':'Nuevo movimiento';$('#amountInput').value=t?formatNumberForInput(t.amount):(preset.amount?formatNumberForInput(preset.amount):'');$('#descriptionInput').value=t?.description||preset.description||'';$('#noteInput').value=t?.note||'';$('#tagsInput').value=t?.tags||'';$('#dateInput').value=t?.tx_date||preset.tx_date||isoLocal(new Date());$('#installmentsInput').value=1;$$('#movementKind button').forEach(b=>b.classList.toggle('active',b.dataset.kind===state.txFormKind));fillAccountSelects(state.data?.accounts||[]);if(t?.account_id)$('#accountSelect').value=String(t.account_id);else if(preset.account_id)$('#accountSelect').value=String(preset.account_id);if(t?.to_account_id)$('#toAccountSelect').value=String(t.to_account_id);renderMovementKind();setCategoryButtonFromId();$('#saveError').textContent='';show('#addSheet',true);setTimeout(()=>$('#amountInput').focus(),150)}
function renderMovementKind(){const transfer=state.txFormKind==='transfer';show('#categoryField',!transfer);show('#toAccountField',transfer);if(!transfer)toggleInstallmentsField();else show('#installmentsField',false)}
function toggleInstallmentsField(){const aid=Number($('#accountSelect').value);const a=(state.data?.accounts||[]).find(x=>Number(x.id)===aid);show('#installmentsField',state.txFormKind==='expense'&&a?.type==='Tarjeta'&&!state.editTxId)}
function setCategoryButtonFromId(){if(!state.txCategoryId){$('#categoryButton').innerHTML='Elegir categoría <b>›</b>';return}const c=(state.data?.categories?.[state.txFormKind]||[]).find(x=>Number(x.id)===Number(state.txCategoryId));$('#categoryButton').innerHTML=c?`${esc(c.label)} <b>›</b>`:'Elegir categoría <b>›</b>'}
function openCategoryPicker(kind,onSelect){state.categoryCallback=onSelect;$('#categorySearch').value='';renderCategoryGrid(kind,'');show('#categorySheet',true)}
function renderCategoryGrid(kind,filter=''){const rows=(state.data?.categories?.[kind]||[]).filter(x=>!filter||x.label.toLowerCase().includes(filter.toLowerCase()));$('#categoryGrid').innerHTML=rows.map(x=>`<button class="category-item" data-id="${x.id}" style="--c:${x.color}"><span class="cat-mark" style="--c:${x.color}">${svgIcon(x.icon)}</span><b>${esc(x.name)}</b>${x.parent?`<small>${esc(x.parent)}</small>`:''}</button>`).join('');$('#categoryGrid').querySelectorAll('.category-item').forEach(b=>b.onclick=()=>{const c=rows.find(x=>Number(x.id)===Number(b.dataset.id));show('#categorySheet',false);state.categoryCallback?.(c);state.categoryCallback=null})}
function parseAmount(raw){let s=String(raw||'').trim().replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');else if(/^\d{1,3}\.\d{3}$/.test(s))s=s.replace('.','');return Number(s)||0}
function formatNumberForInput(v){return Number(v||0).toLocaleString('es-AR',{maximumFractionDigits:2})}
function formatTyping(el){let raw=el.value.replace(/[^0-9,]/g,'');let [i,d]=raw.split(',');i=(i||'').replace(/^0+(?=\d)/,'');i=i.replace(/\B(?=(\d{3})+(?!\d))/g,'.');el.value=d!==undefined?`${i},${d.slice(0,2)}`:i}
async function saveMovement(){const body={id:state.editTxId,kind:state.txFormKind,amount:parseAmount($('#amountInput').value),account_id:Number($('#accountSelect').value),to_account_id:state.txFormKind==='transfer'?Number($('#toAccountSelect').value):null,category_id:state.txFormKind==='transfer'?null:state.txCategoryId,description:$('#descriptionInput').value.trim(),note:$('#noteInput').value.trim(),tags:$('#tagsInput').value.trim(),tx_date:$('#dateInput').value,installments:Number($('#installmentsInput').value||1)};$('#saveError').textContent='';try{await api('/api/transactions',{method:state.editTxId?'PUT':'POST',body:JSON.stringify(body)});show('#addSheet',false);toast(state.editTxId?'Movimiento actualizado':'Movimiento guardado');await refreshBootstrap();if(state.view==='transactions')loadTransactions()}catch(e){$('#saveError').textContent=e.message}}

function analysisQuery(extra={}){const q=new URLSearchParams({mode:state.analysisMode,kind:state.analysisKind});const a=state.analysisAnchor;if(state.analysisMode==='month'){q.set('year',a.getFullYear());q.set('month',a.getMonth()+1)}else if(state.analysisMode==='year')q.set('year',a.getFullYear());else if(['day','week'].includes(state.analysisMode))q.set('date',isoLocal(a));else{q.set('from',$('#analysisFrom').value||isoLocal(new Date(a.getFullYear(),a.getMonth(),1)));q.set('to',$('#analysisTo').value||isoLocal(a))}Object.entries(extra).forEach(([k,v])=>v!=null&&q.set(k,v));return q}
async function loadAnalysis(){try{const j=await api('/api/analysis?'+analysisQuery());state.analysisData=j;$('#analysisPeriodLabel').textContent=analysisLabel(j);$('#analysisPeriodHint').textContent=state.analysisKind==='expense'?'Gastos del período':'Ingresos del período';const total=state.analysisKind==='expense'?j.summary.expense:j.summary.income;$('#analysisSummary').innerHTML=`<div><span>Ingresos</span><strong class="positive">${money(j.summary.income)}</strong></div><i></i><div><span>Gastos</span><strong class="negative">${money(j.summary.expense)}</strong></div><i></i><div><span>Resultado</span><strong class="${j.summary.net<0?'negative':'positive'}">${money(j.summary.net)}</strong></div>`;$('#analysisTotal').textContent=money(total);renderAnalysisCategories(j.categories||[],total);show('#periodInputs',state.analysisMode==='period');if(state.analysisMode==='period'){if(!$('#analysisFrom').value)$('#analysisFrom').value=j.start;if(!$('#analysisTo').value)$('#analysisTo').value=j.end}}catch(e){toast(e.message)}}
function analysisLabel(j){if(state.analysisMode==='month'){return `${months[state.analysisAnchor.getMonth()]} ${state.analysisAnchor.getFullYear()}`}if(state.analysisMode==='year')return String(state.analysisAnchor.getFullYear());if(state.analysisMode==='day')return longDate(j.start);if(state.analysisMode==='week')return `${longDate(j.start)} – ${longDate(j.end)}`;return `${longDate(j.start)} – ${longDate(j.end)}`}
function renderAnalysisCategories(rows,total){const donut=$('#analysisDonut'),el=$('#analysisCategories');if(!rows.length||!total){donut.style.background='#1d2a25';el.innerHTML='<div class="empty">No hay datos en este período.</div>';return}let acc=0,parts=[];rows.slice(0,8).forEach(r=>{const p=num(r.total)/total*100;parts.push(`${r.color} ${acc}% ${acc+p}%`);acc+=p});if(acc<100)parts.push(`#1d2a25 ${acc}% 100%`);donut.style.background=`conic-gradient(${parts.join(',')})`;const max=Math.max(...rows.map(x=>num(x.total)),1);el.innerHTML=rows.map(r=>`<div class="analysis-row" data-id="${r.category_id||''}" style="--c:${r.color}"><span class="cat-mark" style="--c:${r.color}">${svgIcon(r.icon)}</span><div class="analysis-row-body"><div class="analysis-row-top"><span>${esc(r.category)}</span><b>${money(r.total)}</b></div><small>${total?Math.round(num(r.total)/total*100):0}% · ${(r.tx_count||0)+(r.history_rows||0)} registros${r.history_total?' · incluye Excel':''}</small><div class="mini-bar"><i style="width:${num(r.total)/max*100}%"></i></div></div></div>`).join('');el.querySelectorAll('.analysis-row').forEach(r=>r.onclick=()=>r.dataset.id&&openAnalysisCategory(Number(r.dataset.id)))}
async function openAnalysisCategory(categoryId){try{const j=await api('/api/analysis?'+analysisQuery({category_id:categoryId}));const root=(state.analysisData?.categories||[]).find(x=>Number(x.category_id)===categoryId);const rows=j.subcategories||[];$('#detailTitle').textContent=root?.category||'Desglose';$('#detailBody').innerHTML=`<p class="muted">${longDate(j.start)} – ${longDate(j.end)}</p><div class="analysis-list">${rows.length?rows.map(r=>`<div class="analysis-row" data-sub="${r.category_id||''}" style="--c:${r.color}"><span class="cat-mark" style="--c:${r.color}">${svgIcon(r.icon)}</span><div class="analysis-row-body"><div class="analysis-row-top"><span>${esc(r.category)}</span><b>${money(r.total)}</b></div><small>${esc(r.parent_category||'')} ${(r.history_total||0)>0?'· incluye Excel':''}</small></div></div>`).join(''):'<div class="empty">No hay subcategorías para mostrar.</div>'}</div>`;openDetail();$('#detailBody').querySelectorAll('[data-sub]').forEach(el=>el.onclick=()=>{closeDetail();state.txRange={from:j.start,to:j.end};state.txCategory=Number(el.dataset.sub);state.txKind=state.analysisKind;$('#txKind').value=state.txKind;navigate('transactions')})}catch(e){toast(e.message)}}
function shiftAnalysis(dir){const d=new Date(state.analysisAnchor);if(state.analysisMode==='day')d.setDate(d.getDate()+dir);else if(state.analysisMode==='week')d.setDate(d.getDate()+7*dir);else if(state.analysisMode==='month')d.setMonth(d.getMonth()+dir);else if(state.analysisMode==='year')d.setFullYear(d.getFullYear()+dir);state.analysisAnchor=d;loadAnalysis()}

async function loadAccounts(){try{const j=await api('/api/accounts');state.data.accounts=j.accounts;fillAccountSelects(j.accounts);const avail=j.accounts.filter(a=>a.include_in_balance).reduce((s,a)=>s+num(a.balance),0),excluded=j.accounts.filter(a=>!a.include_in_balance).reduce((s,a)=>s+num(a.balance),0),net=avail+excluded;$('#accountsStats').innerHTML=`<div><span>Disponible</span><strong>${money(avail)}</strong></div><i></i><div><span>Separado</span><strong>${money(excluded)}</strong></div><i></i><div><span>Patrimonio</span><strong>${money(net)}</strong></div>`;$('#accountsList').innerHTML=j.accounts.map(a=>`<article class="account-card" data-id="${a.id}" style="--c:${a.color}"><div class="account-top"><span class="account-icon">${svgIcon(accountIcon(a.type))}</span><div><b>${esc(a.name)}</b><small>${esc(a.type)}</small></div><span class="toggle-pill">${a.include_in_balance?'Disponible':'Separada'}</span></div><div class="account-balance">${money(a.balance)}</div><div class="account-foot"><span>Saldo inicial ${money(a.opening_balance)}</span>${a.type==='Tarjeta'?`<span>Límite ${money(a.credit_limit)}</span>`:''}</div></article>`).join('');$('#accountsList').querySelectorAll('[data-id]').forEach(c=>c.onclick=()=>openAccount(Number(c.dataset.id)))}catch(e){toast(e.message)}}
function accountIcon(type){const t=String(type||'').toLowerCase();if(t.includes('tarjeta'))return'card';if(t.includes('banco'))return'bank';if(t.includes('efectivo'))return'cash';if(t.includes('ahorro'))return'savings';return'wallet'}
async function openAccount(id){try{const {account:a}=await api(`/api/account?id=${id}`);let card='',overview=null;if(a.type==='Tarjeta'){const cardData=await api(`/api/card?id=${id}`);overview=cardData.overview;const o=overview;card=`<div class="detail-grid"><div class="detail-stat"><span>Deuda actual</span><b>${money(o.debt)}</b></div><div class="detail-stat"><span>En curso</span><b>${money(o.current_spent)}</b></div><div class="detail-stat"><span>Último cierre</span><b>${money(o.last_statement)}</b></div><div class="detail-stat"><span>Disponible</span><b>${money(o.available_credit)}</b></div></div><div class="detail-actions"><button id="payCard" class="primary wide">Registrar pago</button></div>`}$('#detailTitle').textContent=a.name;$('#detailBody').innerHTML=`<div class="detail-hero"><div class="big-icon">${svgIcon(accountIcon(a.type))}</div><h3>${esc(a.name)}</h3><p>${esc(a.type)} · ${a.include_in_balance?'incluida en saldo disponible':'cuenta separada'}</p><strong>${money(a.balance)}</strong></div>${card}<div class="detail-actions"><button id="toggleAccount" class="soft-button">${a.include_in_balance?'Separar del saldo':'Incluir en saldo'}</button><button id="editAccount" class="soft-button">Editar</button></div>`;openDetail();$('#toggleAccount').onclick=async()=>{await api('/api/accounts/toggle-balance',{method:'POST',body:JSON.stringify({id:a.id,included:!a.include_in_balance})});closeDetail();loadAccounts();refreshBootstrap()};$('#editAccount').onclick=()=>openAccountEditor(a);if($('#payCard'))$('#payCard').onclick=()=>openCardPayment(a,overview)}catch(e){toast(e.message)}}
function openAccountEditor(a=null){const colors=['#66DEB9','#6AA9FF','#B08CFF','#FF8A9B','#E8BD67','#55C8D8','#8FD17D','#E48ABF'];$('#detailTitle').textContent=a?'Editar cuenta':'Nueva cuenta';$('#detailBody').innerHTML=`<label class="field"><span>Nombre</span><input id="accName" value="${escAttr(a?.name||'')}"></label><label class="field"><span>Tipo</span><select id="accType">${['Efectivo','Banco','Billetera','Tarjeta','Ahorro','Otra'].map(x=>`<option ${a?.type===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field"><span>Saldo inicial</span><input id="accOpening" inputmode="decimal" value="${a?formatNumberForInput(a.opening_balance):'0'}"></label><label class="field"><span>Color</span><div class="palette" id="accPalette">${colors.map(c=>`<button class="swatch ${a?.color===c?'active':''}" data-c="${c}" style="--c:${c}"></button>`).join('')}</div></label><label class="field"><span>Incluir en saldo disponible</span><select id="accInclude"><option value="1" ${a?.include_in_balance!==false?'selected':''}>Sí</option><option value="0" ${a?.include_in_balance===false?'selected':''}>No</option></select></label><div id="cardFields"><label class="field"><span>Límite de tarjeta</span><input id="accLimit" inputmode="decimal" value="${a?formatNumberForInput(a.credit_limit):'0'}"></label><div class="editor-row"><label class="field"><span>Cierre</span><input id="accClose" type="number" min="1" max="31" value="${a?.closing_day||1}"></label><label class="field"><span>Vencimiento</span><input id="accDue" type="number" min="1" max="31" value="${a?.due_day||1}"></label></div></div><button id="saveAccount" class="primary full">Guardar cuenta</button>${a?'<button id="deleteAccount" class="ghost-danger full" style="margin-top:8px">Eliminar cuenta</button>':''}`;openDetail();let color=a?.color||colors[0];$('#accPalette').querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{$('#accPalette').querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));s.classList.add('active');color=s.dataset.c});const toggle=()=>show('#cardFields',$('#accType').value==='Tarjeta');$('#accType').onchange=toggle;toggle();$('#saveAccount').onclick=async()=>{const body={id:a?.id,name:$('#accName').value,type:$('#accType').value,opening_balance:parseAmount($('#accOpening').value),color,include_in_balance:$('#accInclude').value==='1',credit_limit:parseAmount($('#accLimit')?.value),closing_day:Number($('#accClose')?.value||1),due_day:Number($('#accDue')?.value||1)};try{await api('/api/accounts',{method:a?'PUT':'POST',body:JSON.stringify(body)});closeDetail();toast('Cuenta guardada');loadAccounts();refreshBootstrap()}catch(e){toast(e.message)}};if(a)$('#deleteAccount').onclick=async()=>{if(!confirm('¿Eliminar esta cuenta?'))return;try{await api(`/api/accounts?id=${a.id}`,{method:'DELETE'});closeDetail();loadAccounts();refreshBootstrap()}catch(e){toast(e.message)}}}
function openCardPayment(a,o={}){$('#detailTitle').textContent=`Pagar ${a.name}`;const others=(state.data?.accounts||[]).filter(x=>Number(x.id)!==Number(a.id));$('#detailBody').innerHTML=`<label class="field"><span>Cómo registrarlo</span><select id="payMode"><option value="external">Ya fue pagada · no tocar otras cuentas</option><option value="account">Desde una cuenta de App Gastos</option></select></label><label class="field" id="paySourceField"><span>Pagar desde</span><select id="paySource">${others.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label><label class="field"><span>Importe</span><input id="payAmount" inputmode="decimal" value="${formatNumberForInput(o.last_statement||o.debt||0)}" placeholder="0"></label><label class="field"><span>Fecha</span><input id="payDate" type="date" value="${isoLocal(new Date())}"></label><button id="savePayment" class="primary full">Registrar pago</button>`;openDetail();const mode=()=>show('#paySourceField',$('#payMode').value==='account');$('#payMode').onchange=mode;mode();$('#savePayment').onclick=async()=>{try{await api('/api/card/payment',{method:'POST',body:JSON.stringify({card_account_id:a.id,mode:$('#payMode').value,source_account_id:Number($('#paySource').value),amount:parseAmount($('#payAmount').value),tx_date:$('#payDate').value})});closeDetail();toast('Pago registrado');loadAccounts();refreshBootstrap()}catch(e){toast(e.message)}}}

async function loadInstallments(){try{const active=$('#installmentFilter').value;const [plans,comm]=await Promise.all([api(`/api/installments?active=${active}`),api('/api/installment-commitments?months=12')]);const rows=plans.plans||[], monthsData=comm.months||[],cur=monthsData[0]||{},next=monthsData[1]||{},remaining=rows.reduce((s,p)=>s+num(p.remaining),0);$('#installmentStats').innerHTML=`<div><span>Este mes</span><strong>${money(cur.total)}</strong></div><i></i><div><span>Próximo</span><strong>${money(next.total)}</strong></div><i></i><div><span>Restante</span><strong>${money(remaining)}</strong></div>`;$('#commitmentStrip').innerHTML=monthsData.map(m=>`<button class="month-card" data-y="${m.year}" data-m="${m.month}"><b>${monthsShort[m.month-1]} ${String(m.year).slice(-2)}</b><strong>${money(m.total)}</strong><small>${m.count} cuotas</small></button>`).join('');$('#commitmentStrip').querySelectorAll('.month-card').forEach((b,i)=>b.onclick=()=>openCommitmentMonth(monthsData[i]));$('#installmentPlans').innerHTML=rows.length?rows.map(p=>`<article class="installment-card" data-id="${p.id}"><div class="installment-head"><span class="cat-mark" style="--c:${p.category_color}">${svgIcon(p.category_icon)}</span><div><b>${esc(p.description||p.category_name||'Compra en cuotas')}</b><small>${esc(p.account_name||'Tarjeta')} · ${esc(p.parent_category_name?`${p.parent_category_name} / ${p.category_name}`:p.category_name||'')}</small></div><span class="progress-label">${Math.round(p.progress||0)}%</span></div><div class="progress"><i style="width:${p.progress||0}%"></i></div><div class="installment-foot"><span>Cuota ${p.current_number||0} de ${p.installments}</span><span>${money(p.base_amount)} / mes</span><span>Restan ${money(p.remaining)}</span></div></article>`).join(''):'<div class="empty glass-card">No hay planes para mostrar.</div>';$('#installmentPlans').querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openInstallment(Number(x.dataset.id),rows.find(p=>Number(p.id)===Number(x.dataset.id))))}catch(e){toast(e.message)}}
function openCommitmentMonth(m){$('#detailTitle').textContent=`${months[m.month-1]} ${m.year}`;$('#detailBody').innerHTML=`<div class="detail-hero"><p>${m.count} cuotas</p><strong>${money(m.total)}</strong></div><div class="compact-list glass-card">${m.items.map(x=>`<div><span>${esc(x.description)}<small>${esc(x.account_name)} · ${x.installment_number}/${x.installment_total}</small></span><b>${money(x.amount)}</b></div>`).join('')}</div>`;openDetail()}
async function openInstallment(id,preview={}){try{const j=await api(`/api/installment?id=${id}`),p={...preview,...j.plan},txs=j.transactions||[],total=Number(p.installments||1),current=Math.max(...txs.map(x=>Number(x.installment_number||0)),0);$('#detailTitle').textContent='Detalle de cuota';let timeline='';for(let n=1;n<=total;n++){const tx=txs.find(x=>Number(x.installment_number)===n);timeline+=`<div class="timeline-row ${tx?'active':''}"><span class="timeline-dot">${tx?'✓':n}</span><div><b>Cuota ${n}/${total}</b><small>${tx?`${longDate(tx.tx_date)} · ${money(tx.amount)}`:'Programada / anterior sin detalle'}</small></div></div>`}$('#detailBody').innerHTML=`<div class="detail-hero"><div class="big-icon">${svgIcon(p.category_icon||'installments')}</div><h3>${esc(p.description||p.category_name||'Compra en cuotas')}</h3><p>${esc(p.account_name||'Tarjeta')}</p><strong>${money(p.base_amount)} / mes</strong></div><div class="detail-grid"><div class="detail-stat"><span>Progreso</span><b>${current}/${total} · ${Math.round(current/total*100)}%</b></div><div class="detail-stat"><span>Total compra</span><b>${money(p.total_amount)}</b></div><div class="detail-stat"><span>Inicio</span><b>${longDate(p.purchase_date)}</b></div><div class="detail-stat"><span>Próxima</span><b>${p.active?longDate(p.next_installment_date):'Finalizada'}</b></div></div><div class="timeline">${timeline}</div><div class="detail-actions">${p.active?'<button id="cancelPlan" class="soft-button wide">Cancelar cuotas restantes</button>':''}<button id="unlinkPlan" class="ghost-danger wide">Quitar plan · conservar gastos</button></div>`;openDetail();if($('#cancelPlan'))$('#cancelPlan').onclick=async()=>{if(!confirm('¿Cancelar las cuotas restantes?'))return;await api('/api/installments/cancel',{method:'POST',body:JSON.stringify({id})});closeDetail();loadInstallments();refreshBootstrap()};$('#unlinkPlan').onclick=async()=>{if(!confirm('¿Quitar el plan y conservar los movimientos ya registrados?'))return;await api('/api/installments/remove',{method:'POST',body:JSON.stringify({id,delete_movements:false})});closeDetail();loadInstallments();refreshBootstrap()}}catch(e){toast(e.message)}}

async function loadFlex(){try{const [j,h]=await Promise.all([api(`/api/flex?week_start=${state.flexWeek}`),api('/api/flex-history')]);const s=j.summary;const end=addDaysISO(state.flexWeek,6);$('#flexWeekLabel').textContent=`${shortDate(state.flexWeek)} – ${longDate(end)}`;$('#flexSummary').innerHTML=`<div><span>Envíos</span><strong>${s.quantity}</strong></div><i></i><div><span>Total</span><strong>${money(s.total)}</strong></div><i></i><div><span>Promedio</span><strong>${money(s.average)}</strong></div>`;$('#flexZones').innerHTML=s.zones.map(z=>`<article class="flex-zone"><div class="flex-zone-top"><div><b>${esc(z.name)}</b><small>${money(z.current_price)} por envío</small></div></div><div class="flex-zone-total">${money(z.total)}</div><div class="stepper"><button data-remove="${z.id}">−</button><strong>${z.quantity} pedidos</strong><button data-add="${z.id}">+</button></div></article>`).join('');$('#flexZones').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>flexDelivery(Number(b.dataset.add),'add'));$('#flexZones').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>flexDelivery(Number(b.dataset.remove),'remove'));$('#flexHistory').innerHTML=(h.weeks||[]).length?(h.weeks||[]).map(w=>`<div><span>${longDate(w.week_start)}<small>${w.quantity} envíos</small></span><b>${money(w.total)}</b></div>`).join(''):'<div class="empty">Todavía no hay semanas anteriores.</div>';const linked=!!j.income_link?.existing_transaction_id;$('#flexIncomeButton').disabled=linked||!s.total;$('#flexIncomeButton').textContent=linked?'Ingreso ya registrado':'Registrar semana como ingreso';$('#flexIncomeButton').onclick=()=>{if(linked||!s.total)return;const flexCat=(state.data?.categories?.income||[]).find(c=>String(c.label).toLowerCase().includes('flex'));openMovement(null,{kind:'income',amount:s.total,category_id:flexCat?.id||null,description:`Mercado Libre Flex · ${shortDate(state.flexWeek)} – ${shortDate(end)}`})};$('#flexRates').onclick=()=>openFlexRates(s.zones)}catch(e){toast(e.message)}}
async function flexDelivery(zone,action){try{await api('/api/flex/delivery',{method:'POST',body:JSON.stringify({zone_id:zone,week_start:state.flexWeek,action,rate_date:isoLocal(new Date())})});loadFlex()}catch(e){toast(e.message)}}
function shiftFlex(n){state.flexWeek=addDaysISO(state.flexWeek,n*7);loadFlex()}
function openFlexRates(zones){$('#detailTitle').textContent='Tarifas Flex';$('#detailBody').innerHTML=`<p class="muted">Cambiar una tarifa hoy no altera semanas anteriores.</p>${zones.map(z=>`<div class="editor-row"><label class="field"><span>${esc(z.name)}</span><input id="rate-${z.id}" inputmode="decimal" value="${formatNumberForInput(z.current_price)}"></label><button class="soft-button" data-save-rate="${z.id}" style="align-self:end;margin-bottom:11px">Guardar</button></div>`).join('')}`;openDetail();$('#detailBody').querySelectorAll('[data-save-rate]').forEach(b=>b.onclick=async()=>{try{await api('/api/flex/rate',{method:'POST',body:JSON.stringify({zone_id:Number(b.dataset.saveRate),price:parseAmount($(`#rate-${b.dataset.saveRate}`).value),effective_from:isoLocal(new Date())})});toast('Tarifa actualizada');closeDetail();loadFlex()}catch(e){toast(e.message)}})}

async function loadReview(){try{const q=state.reviewSource?`?source=${state.reviewSource}`:'';const j=await api('/api/review'+q),items=j.items||[],counts=j.counts||{};$('#reviewStats').innerHTML=`<div><span>Pendientes</span><strong>${counts.all||0}</strong></div><i></i><div><span>Mercado Pago</span><strong>${counts.mercado_pago||0}</strong></div><i></i><div><span>Escaneos</span><strong>${counts.ocr||0}</strong></div>`;$('#reviewList').innerHTML=items.length?items.map(x=>`<article class="review-card" data-id="${x.id}"><div class="review-main"><span class="cat-mark" style="--c:${x.color||'#8fa198'}">${svgIcon(x.icon||'tag')}</span><div><b>${esc(x.description)}</b><small>${longDate(x.tx_date)} · ${esc(x.account_name)}${x.installment_total?` · cuota ${x.installment_current}/${x.installment_total}`:''}</small></div><span class="review-amount ${x.kind==='expense'?'negative':'positive'}">${x.kind==='expense'?'-':'+'}${money(x.amount)}</span></div><div class="review-bottom"><button class="category-chip ${x.category_id?'ready':''}" data-cat="${x.id}">${x.category_id?esc(x.category):'Elegir categoría'}</button><button class="mini-action" data-accept="${x.id}">${svgIcon('check')}</button><button class="mini-action danger" data-ignore="${x.id}">${svgIcon('close')}</button></div></article>`).join(''):'<div class="empty glass-card">No tenés movimientos pendientes.</div>';$('#reviewList').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const item=items.find(x=>Number(x.id)===Number(b.dataset.cat));openCategoryPicker(item.kind,c=>setReviewCategory(item.id,c.id))});$('#reviewList').querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptReview(items.find(x=>Number(x.id)===Number(b.dataset.accept))));$('#reviewList').querySelectorAll('[data-ignore]').forEach(b=>b.onclick=()=>ignoreReview(Number(b.dataset.ignore)));state.data.pending=counts;updateMoreBadges()}catch(e){toast(e.message)}}
async function setReviewCategory(id,categoryId){try{await api('/api/review/category',{method:'POST',body:JSON.stringify({id,category_id:categoryId})});loadReview()}catch(e){toast(e.message)}}
async function acceptReview(item){if(!item.category_id){openCategoryPicker(item.kind,async c=>{await setReviewCategory(item.id,c.id);item.category_id=c.id;acceptReview(item)});return}try{await api('/api/review/accept',{method:'POST',body:JSON.stringify({id:item.id,category_id:item.category_id,remember_rule:true})});toast('Movimiento agregado');loadReview();refreshBootstrap()}catch(e){toast(e.message)}}
async function ignoreReview(id){try{await api('/api/review/ignore',{method:'POST',body:JSON.stringify({id})});loadReview()}catch(e){toast(e.message)}}
async function acceptReady(){try{const j=await api('/api/review/accept-ready',{method:'POST',body:'{}'});toast(`${j.count} movimientos agregados`);loadReview();refreshBootstrap()}catch(e){toast(e.message)}}
async function clearReview(){const group=state.reviewSource==='mercado_pago'?'mercado_pago':(['statement_scan','receipt_scan'].includes(state.reviewSource)?'ocr':'all');if(!confirm('Esto elimina sólo movimientos pendientes. No toca gastos ya aceptados. ¿Continuar?'))return;try{const j=await api('/api/review/clear',{method:'POST',body:JSON.stringify({group})});toast(`${j.count} pendientes eliminados`);loadReview();refreshBootstrap()}catch(e){toast(e.message)}}
function openScan(){const accounts=state.data?.accounts||[];$('#detailTitle').textContent='Escanear comprobante';$('#detailBody').innerHTML=`<p class="muted">Sacá una foto de un ticket o elegí un resumen/PDF. Todo pasa primero por Por revisar.</p><label class="field"><span>Cuenta</span><select id="scanAccount">${accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label class="field"><span>Tipo</span><select id="scanMode"><option value="auto">Detectar automáticamente</option><option value="ticket">Ticket / supermercado</option><option value="statement">Resumen / consumos</option></select></label><label class="field"><span>Fecha si no se detecta</span><input id="scanDate" type="date" value="${isoLocal(new Date())}"></label><button id="chooseScan" class="primary full">Tomar foto o elegir archivo</button>`;openDetail();$('#chooseScan').onclick=()=>{state.scanConfig={account_id:Number($('#scanAccount').value),mode:$('#scanMode').value,fallback_date:$('#scanDate').value};$('#scanFile').value='';$('#scanFile').click()}}
async function handleScanFile(file){if(!file||!state.scanConfig)return;closeDetail();toast('Analizando comprobante…',10000);try{const data=await fileToDataURL(file);const j=await api('/api/scan',{method:'POST',body:JSON.stringify({...state.scanConfig,filename:file.name,data})});toast(`Detectados ${j.detected} · nuevos ${j.stage.inserted}`,2600);state.reviewSource=j.mode==='ticket'?'receipt_scan':'statement_scan';$('#reviewSource').value=state.reviewSource;loadReview();refreshBootstrap()}catch(e){toast(e.message,3000)}}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}

async function loadCategories(){try{const j=await api(`/api/categories?kind=${state.categoriesKind}`),raw=j.raw||[];const roots=raw.filter(x=>x.parent_id==null);$('#categoryGroups').innerHTML=roots.map(r=>{const children=raw.filter(x=>Number(x.parent_id)===Number(r.id));const color=r.color||'#63DAB7',icon=r.icon||'tag';return `<article class="category-group"><div class="category-group-head" data-edit-root="${r.id}"><span class="cat-mark" style="--c:${color}">${svgIcon(icon)}</span><div><b>${esc(r.name)}</b><small>${children.length} subcategorías</small></div><button class="mini-action" data-add-sub="${r.id}">${svgIcon('plus')}</button></div><div class="subcategory-grid">${children.map(c=>`<button class="subcategory" data-edit-sub="${c.id}"><span class="cat-mark" style="--c:${c.color||color}">${svgIcon(c.icon||icon)}</span><b>${esc(c.name)}</b></button>`).join('')}<button class="subcategory sub-add" data-add-sub="${r.id}">${svgIcon('plus')}<b>Agregar</b></button></div></article>`}).join('')||'<div class="empty glass-card">Todavía no hay categorías.</div>';$('#categoryGroups').querySelectorAll('[data-edit-root]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-add-sub]'))return;openCategoryEditor(raw.find(r=>Number(r.id)===Number(x.dataset.editRoot)),raw)});$('#categoryGroups').querySelectorAll('[data-edit-sub]').forEach(x=>x.onclick=()=>openCategoryEditor(raw.find(r=>Number(r.id)===Number(x.dataset.editSub)),raw));$('#categoryGroups').querySelectorAll('[data-add-sub]').forEach(x=>x.onclick=e=>{e.stopPropagation();openCategoryEditor(null,raw,Number(x.dataset.addSub))})}catch(e){toast(e.message)}}
function openCategoryEditor(cat=null,raw=[],parentPreset=null){
  const roots=raw.filter(x=>x.parent_id==null&&Number(x.id)!==Number(cat?.id));
  const colors=['#66DEB9','#6AA9FF','#B08CFF','#FF7184','#E8BD67','#55C8D8','#8FD17D','#E48ABF','#F59E6C','#94A3B8','#4CCFA9','#5B8DEF','#D07AE8','#F078A0','#C0A45F','#6BC8A6'];
  const icons=['tag','food','homecat','car','fuel','health','education','entertainment','subscription','gift','shopping','person','card','cash','wallet','package'];
  let color=cat?.color||roots.find(x=>Number(x.id)===Number(parentPreset))?.color||colors[0];
  let selectedIcon=cat?.icon||roots.find(x=>Number(x.id)===Number(parentPreset))?.icon||'tag';
  $('#detailTitle').textContent=cat?'Editar categoría':parentPreset?'Nueva subcategoría':'Nueva categoría';
  $('#detailBody').innerHTML=`
    <div class="category-editor-preview" id="catPreview"><span class="cat-mark" style="--c:${color}">${svgIcon(selectedIcon)}</span><div><b>${esc(cat?.name||'Nueva categoría')}</b><small>Así se va a ver en App Gastos</small></div></div>
    <label class="field"><span>Nombre</span><input id="catName" value="${escAttr(cat?.name||'')}" placeholder="Ej. Combustible"></label>
    <label class="field"><span>Grupo</span><select id="catParent"><option value="">Categoría principal</option>${roots.map(r=>`<option value="${r.id}" ${(Number(cat?.parent_id||parentPreset)===Number(r.id))?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>
    <label class="field"><span>Color</span><div class="palette refined" id="catPalette">${colors.map(c=>`<button class="swatch ${c===color?'active':''}" data-c="${c}" style="--c:${c}" aria-label="Color"></button>`).join('')}</div></label>
    <label class="field"><span>Icono</span><div class="icon-picker-grid" id="catIconGrid">${icons.map(i=>`<button class="icon-pick ${i===selectedIcon?'active':''}" data-icon-value="${i}" aria-label="${i}">${svgIcon(i)}</button>`).join('')}</div></label>
    <button id="saveCategory" class="primary full">Guardar categoría</button>${cat?'<button id="deleteCategory" class="ghost-danger full" style="margin-top:8px">Eliminar</button>':''}`;
  openDetail();
  const updatePreview=()=>{const mark=$('#catPreview .cat-mark');mark.style.setProperty('--c',color);mark.innerHTML=svgIcon(selectedIcon);$('#catPreview b').textContent=$('#catName').value||'Nueva categoría'};
  $('#catName').oninput=updatePreview;
  $('#catPalette').querySelectorAll('.swatch').forEach(sw=>sw.onclick=()=>{$('#catPalette').querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));sw.classList.add('active');color=sw.dataset.c;updatePreview()});
  $('#catIconGrid').querySelectorAll('.icon-pick').forEach(btn=>btn.onclick=()=>{$('#catIconGrid').querySelectorAll('.icon-pick').forEach(x=>x.classList.remove('active'));btn.classList.add('active');selectedIcon=btn.dataset.iconValue;updatePreview()});
  $('#saveCategory').onclick=async()=>{const body={id:cat?.id,name:$('#catName').value,kind:state.categoriesKind,parent_id:Number($('#catParent').value)||null,color,icon:selectedIcon};try{await api('/api/categories',{method:cat?'PUT':'POST',body:JSON.stringify(body)});closeDetail();toast('Categoría guardada');await refreshBootstrap();loadCategories()}catch(e){toast(e.message)}};
  if(cat)$('#deleteCategory').onclick=async()=>{if(!confirm('¿Eliminar esta categoría?'))return;try{await api(`/api/categories?id=${cat.id}`,{method:'DELETE'});closeDetail();await refreshBootstrap();loadCategories()}catch(e){toast(e.message)}};
}

async function loadCalendar(){try{const j=await api(`/api/calendar?year=${state.calYear}&month=${state.calMonth}`);$('#calLabel').textContent=`${months[state.calMonth-1]} ${state.calYear}`;const first=new Date(state.calYear,state.calMonth-1,1,12),offset=(first.getDay()+6)%7,days=new Date(state.calYear,state.calMonth,0).getDate(),cells=[];for(let i=0;i<offset;i++)cells.push('<div></div>');for(let d=1;d<=days;d++){const iso=`${state.calYear}-${String(state.calMonth).padStart(2,'0')}-${String(d).padStart(2,'0')}`,x=j.days[iso]||{},today=iso===isoLocal(new Date());cells.push(`<button class="calendar-day ${today?'today':''}" data-date="${iso}"><b>${d}</b><div>${x.income?`<small class="day-inc">+${money(x.income)}</small>`:''}${x.expense?`<small class="day-exp">-${money(x.expense)}</small>`:''}</div></button>`)}$('#calendarGrid').innerHTML=cells.join('');$('#calendarGrid').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.txRange={from:b.dataset.date,to:b.dataset.date};state.txCategory=null;navigate('transactions')})}catch(e){toast(e.message)}}
function shiftCalendar(n){const d=new Date(state.calYear,state.calMonth-1+n,1,12);state.calYear=d.getFullYear();state.calMonth=d.getMonth()+1;loadCalendar()}

function openDetail(){show('#detailSheet',true)}function closeDetail(){show('#detailSheet',false)}
function bindEvents(){
  $('#pairButton').onclick=pair;$('#pairCode').onkeydown=e=>e.key==='Enter'&&pair();$('#syncButton').onclick=()=>loadView(state.view).then(()=>toast('Actualizado'));$('#backButton').onclick=goBack;
  $$('[data-open]').forEach(b=>b.onclick=()=>navigate(b.dataset.open));$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view,false));$('#fab').onclick=()=>openMovement();
  $('#prevMonth').onclick=()=>{const d=shiftMonthDate(new Date(state.year,state.month-1,1),-1);state.year=d.getFullYear();state.month=d.getMonth()+1;refreshBootstrap()};$('#nextMonth').onclick=()=>{const d=shiftMonthDate(new Date(state.year,state.month-1,1),1);state.year=d.getFullYear();state.month=d.getMonth()+1;refreshBootstrap()};
  $('#txPrevMonth').onclick=()=>{state.txRange=null;state.txCategory=null;const d=shiftMonthDate(new Date(state.txYear,state.txMonth-1,1),-1);state.txYear=d.getFullYear();state.txMonth=d.getMonth()+1;loadTransactions()};$('#txNextMonth').onclick=()=>{state.txRange=null;state.txCategory=null;const d=shiftMonthDate(new Date(state.txYear,state.txMonth-1,1),1);state.txYear=d.getFullYear();state.txMonth=d.getMonth()+1;loadTransactions()};$('#clearTxRange').onclick=clearTxRange;$('#txKind').onchange=e=>{state.txKind=e.target.value;loadTransactions()};let searchTimer;$('#txSearch').oninput=e=>{state.txSearch=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(loadTransactions,250)};
  $('#closeSheet').onclick=()=>show('#addSheet',false);$('#addSheet').onclick=e=>e.target.id==='addSheet'&&show('#addSheet',false);$$('#movementKind button').forEach(b=>b.onclick=()=>{state.txFormKind=b.dataset.kind;state.txCategoryId=null;$$('#movementKind button').forEach(x=>x.classList.toggle('active',x===b));renderMovementKind();setCategoryButtonFromId()});$('#categoryButton').onclick=()=>openCategoryPicker(state.txFormKind,c=>{state.txCategoryId=c.id;setCategoryButtonFromId()});$('#closeCategories').onclick=()=>show('#categorySheet',false);$('#categorySheet').onclick=e=>e.target.id==='categorySheet'&&show('#categorySheet',false);$('#categorySearch').oninput=e=>renderCategoryGrid(state.txFormKind,e.target.value);$('#amountInput').oninput=e=>formatTyping(e.target);$('#accountSelect').onchange=toggleInstallmentsField;$('#todayButton').onclick=()=>$('#dateInput').value=isoLocal(new Date());$('#saveTransaction').onclick=saveMovement;
  $('#closeDetail').onclick=closeDetail;$('#detailSheet').onclick=e=>e.target.id==='detailSheet'&&closeDetail();
  $$('#analysisKind button').forEach(b=>b.onclick=()=>{state.analysisKind=b.dataset.value;$$('#analysisKind button').forEach(x=>x.classList.toggle('active',x===b));loadAnalysis()});$$('#analysisMode button').forEach(b=>b.onclick=()=>{state.analysisMode=b.dataset.value;$$('#analysisMode button').forEach(x=>x.classList.toggle('active',x===b));loadAnalysis()});$('#analysisPrev').onclick=()=>shiftAnalysis(-1);$('#analysisNext').onclick=()=>shiftAnalysis(1);$('#applyPeriod').onclick=loadAnalysis;
  $('#newAccount').onclick=()=>openAccountEditor();$('#installmentFilter').onchange=loadInstallments;$('#flexPrev').onclick=()=>shiftFlex(-1);$('#flexNext').onclick=()=>shiftFlex(1);
  $('#reviewSource').onchange=e=>{state.reviewSource=e.target.value;loadReview()};$('#acceptReady').onclick=acceptReady;$('#clearReview').onclick=clearReview;$('#scanButton').onclick=openScan;$('#scanFile').onchange=e=>handleScanFile(e.target.files?.[0]);
  $$('#categoryKindTabs button').forEach(b=>b.onclick=()=>{state.categoriesKind=b.dataset.value;$$('#categoryKindTabs button').forEach(x=>x.classList.toggle('active',x===b));loadCategories()});$('#newCategory').onclick=()=>loadCategories().then(async()=>{const j=await api(`/api/categories?kind=${state.categoriesKind}`);openCategoryEditor(null,j.raw||[])});
  $('#calPrev').onclick=()=>shiftCalendar(-1);$('#calNext').onclick=()=>shiftCalendar(1);
}
async function init(){injectStaticIcons();bindEvents();if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});if(!state.token){show('#pairScreen',true);return}try{await api('/api/ping');show('#app',true);await refreshBootstrap();navigate('home',false)}catch(e){unpair()}}
init();setInterval(()=>{if(state.token&&!document.hidden&&state.view==='home')refreshBootstrap()},30000);
